/* FINCA LA CARLA - galerias.js (manifesto de fotos del Drive) */
window.Finca = window.Finca || {};
window.Finca.galerias = {
    "actividad_petroglifos":  [
                                  "images/fotos/g Que hacer/Pinturas y geroglifos/Destacada (1)/Animana_San_Antonio_Cerro_Pachamama_Nano_Escudero__Banner_3_.jpg",
                                  "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cardones_Nano_Escudero_Banner (10).jpg",
                                  "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cardones_Nano_Escudero_Banner (3).jpg",
                                  "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cardones_Nano_Escudero_Banner (4).jpg",
                                  "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cardones_Nano_Escudero_Banner (5).jpg",
                                  "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cerro_Pachamama_Nano_Escudero_Baja_1_.jpg",
                                  "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cerro_Pachamama_Nano_Escudero_Baja_2_.jpg"
                              ],
    "exterior":  [
                     "images/fotos/j Exterior o jardines/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Jardin (7).jpg",
                     "images/fotos/j Exterior o jardines/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Jardin (1).jpg",
                     "images/fotos/j Exterior o jardines/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Jardin (2).jpg",
                     "images/fotos/j Exterior o jardines/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Jardin (3).jpg",
                     "images/fotos/j Exterior o jardines/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Jardin (4).jpg",
                     "images/fotos/j Exterior o jardines/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Jardin (5).jpg",
                     "images/fotos/j Exterior o jardines/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Jardin.png",
                     "images/fotos/j Exterior o jardines/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Jardin (6).jpg"
                 ],
    "quehacer":  [
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Cabalgata.png",
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(1).jpg",
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(2).jpg",
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(3).jpg",
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(4).jpg",
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(5).jpg",
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(6).jpg",
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Secundarias (resto)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero (30).jpg",
                     "images/fotos/g Que hacer/Cabalgatas en Corralito/Secundarias (resto)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero (31).jpg",
                     "images/fotos/g Que hacer/Pinturas y geroglifos/Destacada (1)/Animana_San_Antonio_Cerro_Pachamama_Nano_Escudero__Banner_3_.jpg",
                     "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cardones_Nano_Escudero_Banner (10).jpg",
                     "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cardones_Nano_Escudero_Banner (3).jpg",
                     "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cardones_Nano_Escudero_Banner (4).jpg",
                     "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cardones_Nano_Escudero_Banner (5).jpg",
                     "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cerro_Pachamama_Nano_Escudero_Baja_1_.jpg",
                     "images/fotos/g Que hacer/Pinturas y geroglifos/Principales (6)/Animana_San_Antonio_Cerro_Pachamama_Nano_Escudero_Baja_2_.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 1.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 2.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 3.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 4.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 5.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 6.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 7.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 8.jpg",
                     "images/fotos/g Que hacer/RIO FOTO 9.jpg",
                     "images/fotos/g Que hacer/RUTA 68 FOTO 1.jpg",
                     "images/fotos/g Que hacer/RUTA 68 FOTO 2.jpg",
                     "images/fotos/g Que hacer/SENDERO FOTO 1.jpg",
                     "images/fotos/g Que hacer/SENDERO FOTO 2.jpg",
                     "images/fotos/g Que hacer/SENDERO FOTO 3.jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero.png",
                     "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (1).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (2).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (3).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (4).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (5).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (6).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (20).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (21).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (22).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (23).jpg",
                     "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (24).jpg"
                 ],
    "livings":  [
                    "images/fotos/d Servicios/10 Living y espacios comunes/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Living.jpg",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Living (1).png",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Living (1b).jpg",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Living (1c).jpeg",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Living (2).jpg",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Living (2b).jpeg",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Living (3).jpg",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Living (21).jpeg",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Living (21).jpg",
                    "images/fotos/d Servicios/10 Living y espacios comunes/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Living (22).jpg"
                ],
    "pileta":  [
                   "images/fotos/d Servicios/7 Pileta/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Pileta.png",
                   "images/fotos/d Servicios/7 Pileta/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Pileta (1).png",
                   "images/fotos/d Servicios/7 Pileta/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Pileta (1b).jpeg",
                   "images/fotos/d Servicios/7 Pileta/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Pileta (1c).jpg",
                   "images/fotos/d Servicios/7 Pileta/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Pileta (1d).png",
                   "images/fotos/d Servicios/7 Pileta/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Pileta (2).jpeg",
                   "images/fotos/d Servicios/7 Pileta/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Pileta (2b).jpg",
                   "images/fotos/d Servicios/7 Pileta/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Pileta (24).jpg",
                   "images/fotos/d Servicios/7 Pileta/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Pileta (25).jpg"
               ],
    "eventos":  [
                    "images/fotos/f Eventos/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Living.jpg",
                    "images/fotos/f Eventos/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Galeria.jpg",
                    "images/fotos/f Eventos/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Living (1).png",
                    "images/fotos/f Eventos/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Parrilla.jpg",
                    "images/fotos/f Eventos/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Pileta.png"
                ],
    "actividad_obras":  [
                            "images/fotos/g Que hacer/Trekking por el río/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero.png",
                            "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (1).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (2).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (3).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (4).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (5).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (6).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (20).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (21).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (22).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (23).jpg",
                            "images/fotos/g Que hacer/Trekking por el río/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Trekking_Nano_Escudero (24).jpg"
                        ],
    "arquitectura":  [
                         "images/fotos/i Arquitectura/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura.jpg",
                         "images/fotos/i Arquitectura/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (1).jpeg",
                         "images/fotos/i Arquitectura/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (1).jpg",
                         "images/fotos/i Arquitectura/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (2).jpg",
                         "images/fotos/i Arquitectura/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (3).jpg",
                         "images/fotos/i Arquitectura/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (4).jpg",
                         "images/fotos/i Arquitectura/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (5).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (50).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (51).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (52).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (53).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (54).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (55).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (56).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (57).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (58).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (59).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (60).jpeg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (60).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (61).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (62).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (63).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (64).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (65).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (66).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (67).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (68).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (69).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (70).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (71).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (72).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (73).jpg",
                         "images/fotos/i Arquitectura/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Arquitectura (90).png"
                     ],
    "sustentabilidad":  [
                            "images/fotos/m Sustentabilidad/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Sustentabilidad.jpg",
                            "images/fotos/m Sustentabilidad/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Sustentabilidad (1).png",
                            "images/fotos/m Sustentabilidad/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Sustentabilidad (1b).jpg",
                            "images/fotos/m Sustentabilidad/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Sustentabilidad (2).png",
                            "images/fotos/m Sustentabilidad/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Sustentabilidad (2b).jpg",
                            "images/fotos/m Sustentabilidad/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Sustentabilidad (3).jpg",
                            "images/fotos/m Sustentabilidad/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Sustentabilidad (4).jpg"
                        ],
    "bano":  [
                 "images/fotos/b Habitaciones/z Baño/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Baño.png",
                 "images/fotos/b Habitaciones/z Baño/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Baño (1).jpg",
                 "images/fotos/b Habitaciones/z Baño/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Baño (1).png",
                 "images/fotos/b Habitaciones/z Baño/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Baño (2).jpg",
                 "images/fotos/b Habitaciones/z Baño/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Baño (3).jpg",
                 "images/fotos/b Habitaciones/z Baño/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Baño (4).jpg",
                 "images/fotos/b Habitaciones/z Baño/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Baño (5).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (10).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (11).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (12).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (13).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (14).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (15).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (16).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (17).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (8).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (8).png",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Baño (9).jpg",
                 "images/fotos/b Habitaciones/z Baño/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Gastronomia (3).jpg"
             ],
    "actividad_cabalgata":  [
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Cabalgata.png",
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(1).jpg",
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(2).jpg",
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(3).jpg",
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(4).jpg",
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(5).jpg",
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Principales (6)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero(6).jpg",
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Secundarias (resto)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero (30).jpg",
                                "images/fotos/g Que hacer/Cabalgatas en Corralito/Secundarias (resto)/Animana_Salta_Argentina_Cabalgata_Nano_Escudero (31).jpg"
                            ],
    "recreacion":  [
                       "images/fotos/d Servicios/5 Recreacion/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Living.jpg",
                       "images/fotos/d Servicios/5 Recreacion/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Living (3).jpg",
                       "images/fotos/d Servicios/5 Recreacion/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Recreacion (2).png",
                       "images/fotos/d Servicios/5 Recreacion/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Recreacion.jpeg"
                   ],
    "habitaciones":  [
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_HabitacionDest.jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (1).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (2).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (3).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (4).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (5).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (6).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (10).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (11).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (12).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (13).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (14).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (15).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (16).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (17).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (18).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (19).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (20).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (21).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (22).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (23).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (24).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (25).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (26).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (27).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (28).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (29).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (30).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (31).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (32).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (33).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (34).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (35).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (36).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (37).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (38).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (39).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (40).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (41).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (42).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (43).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (8).jpg",
                         "images/fotos/b Habitaciones/Habitacion Categoría A/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Habitacion  (9).jpg"
                     ],
    "galeria_arq":  [
                        "images/fotos/d Servicios/11 Galería/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Galeria.jpg",
                        "images/fotos/d Servicios/11 Galería/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (1).jpg",
                        "images/fotos/d Servicios/11 Galería/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (1b).png",
                        "images/fotos/d Servicios/11 Galería/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (2).jpg",
                        "images/fotos/d Servicios/11 Galería/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (2b).png",
                        "images/fotos/d Servicios/11 Galería/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (3).jpg",
                        "images/fotos/d Servicios/11 Galería/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (4).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (30).jpeg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (31 b).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (31 c).png",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (31).jpeg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (32 b).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (32).jpeg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (33 b).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (33).jpeg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (34 b).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (34).jpeg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (35).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (36).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (37).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (38).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (40).jpg",
                        "images/fotos/d Servicios/11 Galería/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Galeria (50).png"
                    ],
    "artesanias":  [
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos.jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (1).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (2).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (3).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (4).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (5).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (6).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (19).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (19).png",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (20).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (21).jpg",
                       "images/fotos/d Servicios/9 Artesanías y Product Regional/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Artesanias_Productos (22).jpg"
                   ],
    "desayuno":  [
                     "images/fotos/c Gastronomía/z Otras/Desayunos/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Desayuno.jpeg"
                 ],
    "quienes":  [
                    "images/fotos/h Quienes somos/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Quienes_Somos.jpg",
                    "images/fotos/h Quienes somos/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Quienes_Somos (1).jpg",
                    "images/fotos/h Quienes somos/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Quienes_Somos (2).jpg",
                    "images/fotos/h Quienes somos/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Quienes_Somos (3).jpg"
                ],
    "gastronomia":  [
                        "images/fotos/c Gastronomía/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Gastronomia.png",
                        "images/fotos/c Gastronomía/Imagen2.png",
                        "images/fotos/c Gastronomía/Principales (6)/Empanadas_Nano_Escudero 2 .jpg",
                        "images/fotos/c Gastronomía/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Gastronomia (1).jpg",
                        "images/fotos/c Gastronomía/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Gastronomia (111).png",
                        "images/fotos/c Gastronomía/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Gastronomia (112).jpg",
                        "images/fotos/c Gastronomía/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Gastronomia (2).jpg",
                        "images/fotos/c Gastronomía/Principales (6)/Locro_EM_MinTurSla (1).jpg",
                        "images/fotos/c Gastronomía/Secundarias (resto)/Finca_La_Carla_Animana_Salta_Argentina_Gastronomia (25).jpeg",
                        "images/fotos/c Gastronomía/z Otras/Desayunos/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Desayuno.jpeg",
                        "images/fotos/c Gastronomía/z Otras/Salón Comedor/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Comedor.jpg",
                        "images/fotos/c Gastronomía/z Otras/Salón Comedor/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Comedor (1).jpg",
                        "images/fotos/c Gastronomía/z Otras/Salón Comedor/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Comedor (1).png",
                        "images/fotos/c Gastronomía/z Otras/Salón Comedor/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Comedor (2).jpg",
                        "images/fotos/c Gastronomía/z Otras/Salón Comedor/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Comedor (2).png",
                        "images/fotos/c Gastronomía/z Otras/Salón Desayunador/Destacada (1)/Finca_La_Carla_Animana_Salta_Argentina_Desayunador (1).png",
                        "images/fotos/c Gastronomía/z Otras/Salón Desayunador/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Desayunador (1).jpeg",
                        "images/fotos/c Gastronomía/z Otras/Salón Desayunador/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Desayunador (1).jpg",
                        "images/fotos/c Gastronomía/z Otras/Salón Desayunador/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Desayunador (2).jpeg",
                        "images/fotos/c Gastronomía/z Otras/Salón Desayunador/Principales (6)/Finca_La_Carla_Animana_Salta_Argentina_Desayunador (3).jpeg"
                    ]
};

/* Ajusta las rutas relativas según la ubicación de la página.
   Cada página declara window.FINCA_BASE: "" en la raíz o "../" en html/. */
(function () {
    "use strict";
    var base = window.FINCA_BASE || "";
    if (!base) { return; }
    var g = window.Finca && window.Finca.galerias;
    if (!g) { return; }
    Object.keys(g).forEach(function (clave) {
        g[clave] = g[clave].map(function (ruta) {
            return ruta.indexOf(base) === 0 ? ruta : base + ruta;
        });
    });
})();

