/* ==========================================================================
   FINCA LA CARLA — Diccionario de idiomas (ES / EN)
   El sitio se construye en español; los textos llevan atributos data-i18n.
   Este archivo contiene la traducción fiel al inglés de todo el contenido.
   ========================================================================== */
window.LANG = {
  "es": {
    /* ---------- General ---------- */
    "reservar": "RESERVAR",
    "enviar": "Enviar",
    "volver": "Volver",
    "verMas": "Ver más",
    "leerMas": "Leer más",
    "home": "Home",
    "cerrar": "Cerrar",
    "anterior": "Anterior",
    "siguiente": "Siguiente",
    "direccion_corta": "Paraje San Antonio s/n, Animana, Salta, Argentina",
    "conocer": "Conocé Finca La Carla",
    "descubrir": "Descubrir",
    "eyebrow_hero": "Posada boutique · Valle Calchaquí",
    "eyebrow_hero_sub": "Paraje San Antonio · Animana · Salta",
    "eyebrow_pres": "Bienvenidos al paraje San Antonio",
    "eyebrow_servicios": "Nuestra propuesta",
    "eyebrow_historia": "Una historia de familia",
    "eyebrow_ofrecemos": "Valores que nos definen",
    "eyebrow_testimonios": "Experiencias de huéspedes",
    "eyebrow_donde": "Nuestra ubicación",

    /* ---------- Navegación ---------- */
    "nav_home": "Home",
    "nav_habitaciones": "Habitaciones",
    "nav_gastronomia": "Gastronomía",
    "nav_servicios": "Servicios",
    "nav_eventos": "Eventos",
    "nav_quehacer": "Qué hacer",
    "nav_quienessomos": "Quiénes somos",
    "nav_fotos": "Fotos",
    "nav_contacto": "Contacto",

    /* ---------- Hero / banner ---------- */
    "hero_lema": "Una propuesta terrenal",

    /* ---------- Presentación breve ---------- */
    "pres_titulo": "Una propuesta terrenal",
    "pres_subtitulo": "Naturaleza, producción y descanso en el Valle Calchaquí",
    "pres_texto": "Finca La Carla es una posada boutique en el paraje San Antonio, Animana, rodeada por dos hectáreas de producción agroecológica. Construida con piedra, madera y adobe, combina una estética rústica y minimalista con una mirada sustentable: energía solar, reutilización de agua y productos de la finca que llegan a la mesa. Un lugar pensado para bajar el ritmo, descansar y compartir.",
    "pres_boton": "Conocé Finca La Carla",

    /* ---------- Nuestros servicios ---------- */
    "servicios_titulo": "Nuestros servicios",
    "serv_gastronomia": "Gastronomía",
    "serv_eventos": "Eventos",
    "serv_quehacer": "Qué hacer",
    "serv_recreacion": "Recreación",
    "serv_pileta": "Pileta",
    "serv_artesanias": "Artesanías y productos regionales",
    "serv_livings": "Livings y espacios comunes",
    "serv_galeria": "Galería física",
    "serv_informacion": "Información útil",
    "serv_faq": "Preguntas frecuentes",

    /* ---------- Quiénes somos (resumen) ---------- */
    "historia_titulo": "Una historia hecha despacio",
    "historia_texto": "Diego imaginó este proyecto a comienzos de los años 2000 y lo construyó durante dos décadas junto a personas de la comunidad. Hoy, con Marcela, recibe personalmente a cada huésped y continúa dando forma a una finca donde diseño, producción y cuidado del ambiente son parte de la misma historia.",
    "historia_enlace": "Conocé nuestra historia",

    /* ---------- Qué ofrecemos ---------- */
    "ofrecemos_titulo": "Qué ofrecemos",
    "ofre_sust_titulo": "Sustentabilidad real",
    "ofre_sust_texto": "Energía solar, reutilización de agua, compostaje y producción agroecológica forman parte del funcionamiento cotidiano de la finca.",
    "ofre_prod_titulo": "Producción propia",
    "ofre_prod_texto": "Frutas, hortalizas, mermeladas, vinos y sidras nacen en la finca y llegan a desayunos, almuerzos, cenas y productos para llevar.",
    "ofre_atencion_titulo": "Atención de sus dueños",
    "ofre_atencion_texto": "Diego y Marcela reciben y acompañan personalmente a los huéspedes, con una atención cercana y pendiente de cada necesidad.",
    "ofre_ritmo_titulo": "Ritmo del valle",
    "ofre_ritmo_texto": "Naturaleza, silencio y un paisaje abierto invitan a bajar el ritmo y disfrutar una estadía tranquila en el paraje San Antonio.",

    /* ---------- Testimonios ---------- */
    "testimonios_titulo": "Testimonios",
    "test_marcelo": "Un lugar soñado en la montaña para conectarse en serio. Todo está muy cuidado y bien logrado. Se destacan la atención cordial y genuina de sus dueños, la comida, los dulces caseros y los vinos que elaboran.",
    "test_eugenia": "Nos alojamos en pareja y desde el primer día la experiencia fue hermosa. Diego y Marcela nos atendieron con mucha calidez. Disfrutamos los desayunos, las cenas, los productos cosechados allí y especialmente sus vinos.",
    "test_nelly": "Cada espacio refleja mucho trabajo, amor y buen gusto. La calidez con la que nos atendieron fue maravillosa, la limpieza impecable y nos encantó que tantos productos salieran directamente de la tierra y la huerta.",
    "test_maya": "Anfitriones maravillosos, habitaciones acogedoras e impecables, un ambiente encantador y comida increíblemente deliciosa. La finca es un oasis de relajación, con mucha atención al detalle. Ya estoy deseando volver.",
    "test_marie": "Un lugar excepcional, tranquilo, íntimo y relajante, con un desayuno exquisito elaborado con ingredientes frescos y dueños acogedores y cálidos. Fue el mejor lugar de nuestro recorrido de dos meses y medio por Sudamérica.",

    /* ---------- Dónde estamos ---------- */
    "donde_titulo": "Dónde estamos",
    "donde_texto": "Finca La Carla está en el paraje San Antonio, municipio de Animana, a 18 km de Cafayate. Los últimos 7 km son de ripio, entre piedemonte, algarrobos y paisajes propios del Valle Calchaquí.",
    "donde_direccion": "Paraje San Antonio s/n, Animana, Salta. Argentina.",
    "donde_abrir": "Abrir en Google Maps",

    /* ---------- Footer ---------- */
    "footer_navegacion": "Navegación",
    "footer_legal": "Legal",
    "footer_terminos": "Términos y condiciones",
    "footer_cookies": "Política de cookies",
    "footer_sustentabilidad": "Sustentabilidad",
    "footer_comunidad": "Compromiso con la comunidad",
    "footer_contacto": "Contacto",
    "footer_whatsapp": "WhatsApp principal",
    "footer_cel": "Teléfono celular 2",
    "footer_email_general": "Email general",
    "footer_email_reservas": "Reservas",
    "footer_derechos": "© {año} Finca La Carla. Todos los derechos reservados.",

    /* ---------- Habitaciones ---------- */
    "hab_titulo": "Siete habitaciones cálidas, simples y pensadas para descansar",
    "hab_intro": "Las siete habitaciones forman parte de una misma categoría y comparten el carácter rústico y minimalista de la finca, con materiales y tonos vinculados a la tierra. Todas cuentan con baño privado, calefacción por radiadores, Wi-Fi, placard y secador de pelo. Cinco están en planta baja y dos en planta alta. La mayoría son triples y una de ellas ofrece un gran ventanal con vista al valle y al cielo nocturno.",
    "hab_galeria": "Galería de habitaciones",
    "hab_con_titulo": "Todas cuentan con",
    "hab_con_1": "Baño privado",
    "hab_con_2": "Inodoro",
    "hab_con_3": "Bidet",
    "hab_con_4": "Calefacción por radiadores",
    "hab_con_5": "Wi-Fi",
    "hab_con_6": "Placard",
    "hab_con_7": "Secador de pelo",
    "hab_con_8": "Ropa de cama",
    "hab_con_9": "Toallas",
    "hab_sin_titulo": "No cuentan con",
    "hab_sin_1": "Televisión dentro de la habitación",
    "hab_sin_2": "Aire acondicionado",
    "hab_sin_3": "Caja de seguridad",
    "hab_sin_4": "Minibar",
    "hab_sin_5": "Pava eléctrica",
    "hab_sin_6": "Cafetera",
    "hab_smarttv": "Hay Smart TV únicamente en un espacio común.",
    "hab_capacidad_titulo": "Capacidad y distribución",
    "hab_cap_triples": "5 habitaciones triples, con 1 cama matrimonial y 1 cama simple.",
    "hab_cap_doble": "1 habitación doble.",
    "hab_cap_doblem": "1 habitación doble con 1 cama matrimonial.",
    "hab_cap_total": "Capacidad total máxima: 21 personas, contemplando la posibilidad de agregar camas adicionales según disponibilidad.",
    "hab_cap_pb": "5 habitaciones en planta baja.",
    "hab_cap_pa": "2 habitaciones en planta alta, con acceso por escalera.",
    "hab_cap_superficie": "Superficie aproximada de cada habitación: 18 m².",
    "hab_adicional_titulo": "Información adicional",
    "hab_adic_1": "Cama adicional a pedido cuando la disponibilidad general lo permita y siempre que el hotel no esté totalmente lleno. Sin costo adicional.",
    "hab_adic_2": "Cuna a pedido, sin costo adicional.",
    "hab_adic_3": "La habitación número 3 es la única con bañera con jacuzzi.",
    "hab_adic_4": "Algunas habitaciones tienen vista hacia el viñedo y otras hacia el ingreso de la finca.",
    "hab_adic_5": "Existe una habitación con gran ventanal y vista al Valle Calchaquí, especialmente valorada por parejas y por la vista nocturna.",
    "hab_accesibilidad": "Por los desniveles y escaleras, las instalaciones no están adaptadas para personas con movilidad reducida.",

    /* ---------- Gastronomía ---------- */
    "gastro_titulo": "Gastronomía",
    "gastro_intro": "Sabores caseros y productos de la propia finca",
    "gastro_acerca_titulo": "Acerca de nuestra cocina",
    "gastro_acerca": "El desayuno está incluido e integra café, leche, tés, tostadas, manteca, yogur y granola caseros, además de mermeladas elaboradas en la finca con frutas de estación. Según el día se suman budines, tortas, masas dulces y pan de bollo de vecinos de la comunidad. Los almuerzos y cenas se preparan a pedido y tienen costo adicional: pueden incluir cazuela de cabrito, tartas con productos de la huerta, empanadas árabes y pastas caseras. También hay opciones vegetarianas, veganas e infantiles a pedido, vinos y sidras propios y viandas para picnic. Las comidas se coordinan con anticipación y buscan aprovechar productos de la finca y de productores cercanos.",
    "gastro_desayuno_titulo": "Desayuno",
    "gastro_desayuno_texto": "Está incluido en todas las reservas. Puede incluir:",
    "gastro_desayuno_1": "Café",
    "gastro_desayuno_2": "Leche",
    "gastro_desayuno_3": "Distintos tés",
    "gastro_desayuno_4": "Tostadas",
    "gastro_desayuno_5": "Manteca",
    "gastro_desayuno_6": "Yogur casero",
    "gastro_desayuno_7": "Granola casera",
    "gastro_desayuno_8": "Budines",
    "gastro_desayuno_9": "Tortas",
    "gastro_desayuno_10": "Masas dulces",
    "gastro_desayuno_11": "Pan de bollo elaborado por vecinos",
    "gastro_mermeladas": "Mermeladas caseras según disponibilidad: damasco, durazno, cayote, membrillo, ciruela, tomate y manzana.",
    "gastro_almuerzos_titulo": "Almuerzos y cenas",
    "gastro_almuerzos_texto": "No funcionan como restaurante abierto con carta permanente. Se preparan a pedido, tienen costo adicional y se recomienda solicitarlos con 3 o 4 horas de anticipación. Existe una cocinera local que puede preparar las comidas. Algunos de los platos:",
    "gastro_plato_1": "Cazuela de cabrito",
    "gastro_plato_2": "Tartas o tarteletas con productos de la huerta",
    "gastro_plato_3": "Preparaciones con zucchini y zapallitos",
    "gastro_plato_4": "Empanadas árabes",
    "gastro_plato_5": "Pastas caseras",
    "gastro_plato_6": "Agnolotti de ricota, nuez y jamón",
    "gastro_plato_7": "Fideos caseros",
    "gastro_plato_8": "Salsa boloñesa",
    "gastro_plato_9": "Salsa fileto",
    "gastro_plato_10": "Strudel de manzana elaborado con manzanas de la finca",
    "gastro_plato_11": "Helados según temporada",
    "gastro_dietas_titulo": "Dietas especiales",
    "gastro_dietas_texto": "Pueden prepararse a pedido: menú vegetariano, menú vegano y menú infantil. Actualmente no existe una propuesta sin TACC confirmada.",
    "gastro_bebidas_titulo": "Bebidas",
    "gastro_bebidas_1": "Vinos elaborados en la finca",
    "gastro_bebidas_2": "Sidras elaboradas en la finca",
    "gastro_bebidas_3": "Cerveza",
    "gastro_bebidas_4": "Gaseosas",
    "gastro_bebidas_5": "Agua",
    "gastro_bebidas_6": "Soda",
    "gastro_bebidas_nota_1": "El agua y la soda suelen ser invitación de la casa.",
    "gastro_bebidas_nota_2": "Pueden ofrecerse a pedido durante la sobremesa aguardiente, grapa y coñac. Hay una cava con vinos propios; no existe bar independiente.",
    "gastro_viandas": "No existe servicio a la habitación. Sí pueden prepararse viandas para picnic, excursiones o viajes, previa coordinación.",

    /* ---------- Servicios ---------- */
    "serv_titulo": "Servicios simples, atención cercana y espacios para disfrutar",
    "serv_intro": "La estadía combina atención directa de Diego y Marcela con servicios pensados para acompañar el descanso: desayuno incluido, limpieza diaria, lavandería sin costo en estadías prolongadas, guardado de equipaje, Wi-Fi Starlink, estacionamiento, pileta de temporada, biblioteca, juegos de mesa y espacios comunes. También pueden coordinarse comidas, actividades y servicios de terceros.",
    "serv_atencion_titulo": "Atención al huésped",
    "serv_atencion_texto": "La atención es realizada directamente por Diego y Marcela, desde la llegada y la explicación del funcionamiento de la casa hasta la asistencia con equipaje, desayunos y coordinación de comidas o actividades.",
    "serv_atencion_1": "Limpieza diaria",
    "serv_atencion_2": "Cambio de ropa blanca cada dos días o a solicitud",
    "serv_atencion_3": "Lavandería sin costo para estadías prolongadas",
    "serv_atencion_4": "Guardado de equipaje sin costo",
    "serv_atencion_5": "Cunas",
    "serv_atencion_6": "Contacto con remises, guías locales, empresas de turismo y cabalgatas cuando se requiera",
    "serv_atencion_nota": "Los traslados, el alquiler de vehículos, el trekking guiado y las cabalgatas operados por terceros no son servicios propios de la finca.",
    "serv_recreacion_titulo": "Tiempo para leer, jugar y compartir",
    "serv_recreacion_texto": "La recreación dentro de la finca está pensada para disfrutar el tiempo sin apuro. En el estar común hay una biblioteca con distintas colecciones, juegos de mesa y un Smart TV de uso compartido. Los huéspedes pueden tomar libros, jugar en familia o elegir una película. También es posible, según la época y la actividad de la finca, acercarse a tareas vinculadas con la huerta, la cosecha de frutas o uvas y la elaboración de conservas. Todo está incluido para quienes se hospedan y no requiere reserva previa.",
    "serv_pileta_titulo": "Pileta entre árboles y paisaje",
    "serv_pileta_texto": "La pileta exterior mide aproximadamente 7 x 4,5 metros y tiene 1,50 metro de profundidad. Se utiliza principalmente durante el verano y también en algunos días cálidos de primavera. Su uso está incluido para los huéspedes y no tiene costo adicional. El sector cuenta con solárium, reposeras y sombra natural de los árboles; se pueden solicitar toallas y coordinar bebidas o meriendas. Desde allí se disfruta la apertura hacia el Valle Calchaquí y la cercanía con la galería y el parque. No hay bañero, por lo que los niños deben permanecer bajo supervisión adulta y se solicita evitar juegos bruscos. La pileta no es climatizada: su calefacción mediante bomba de calor es solamente un proyecto.",
    "serv_artesanias_titulo": "Productos nacidos en la finca",
    "serv_artesanias_texto": "En el hotel se exhiben y venden productos elaborados a partir de la producción de la finca: mermeladas de ciruela, damasco, membrillo, durazno y cayote, mieles orgánicas, vinos, sidra, aguardiente, coñac, brandy y frutos secos como nueces. También hay piezas artesanales con diseños de Marcela, entre ellas chales, carteras, pantalones, suéteres, camisas, ponchos y ruanas; algunas son tejidas y otras de lino. Muchos de los alimentos y bebidas que se venden son los mismos que forman parte de desayunos, almuerzos, cenas y sobremesas. Los medios de pago habituales son efectivo y transferencia.",
    "serv_livings_titulo": "Espacios para compartir sin apuro",
    "serv_livings_texto": "Los espacios comunes prolongan el carácter cálido y despojado de las habitaciones. La cocina, el desayunador, el comedor y el estar con hogar a leña se integran como lugares para descansar, leer, conversar o compartir una comida. Hay una biblioteca, juegos de mesa y un Smart TV de uso común. El mobiliario, las lámparas, la madera, la piedra y los tonos de la tierra acompañan una ambientación rústica y minimalista, pensada para que cada ambiente conserve identidad sin perder sencillez.",
    "serv_galeria_titulo": "Una galería abierta al Valle",
    "serv_galeria_texto": "La gran galería es uno de los espacios centrales de Finca La Carla. Desde allí se abre una vista amplia hacia el Valle Calchaquí y se conecta el sector de habitaciones con el parque y la pileta. En primavera y verano se convierte en uno de los lugares más elegidos para descansar, conversar y compartir comidas. Su escala permite también recibir encuentros y almuerzos grupales. La piedra, la madera y los tonos naturales mantienen el lenguaje rústico y sobrio de toda la casa.",

    /* ---------- Eventos ---------- */
    "eventos_titulo": "Encuentros rodeados de naturaleza",
    "eventos_texto": "La finca recibe encuentros familiares, cumpleaños, bautismos, retiros, capacitaciones y reuniones de grupos. La amplia galería ha sido utilizada para almuerzos de más de 50 personas y el parque ofrece sectores bajo los árboles para actividades al aire libre. Se dispone de mesas, sillas, Wi-Fi y sonido; cuando el evento requiere más equipamiento, quienes contratan pueden incorporarlo por su cuenta. La gastronomía o el coffee break pueden coordinarse previamente. El presupuesto se solicita con una anticipación aproximada de 15 días a un mes. Hasta 21 personas pueden hospedarse en las siete habitaciones, contemplando camas adicionales según disponibilidad.",
    "eventos_nota_1": "La galería y el parque son los espacios utilizados; no existe un salón específico para eventos.",
    "eventos_equipo_titulo": "Equipamiento confirmado",
    "eventos_equipo_1": "Mesas",
    "eventos_equipo_2": "Sillas",
    "eventos_equipo_3": "Wi-Fi",
    "eventos_equipo_4": "Sonido",
    "eventos_nota_2": "La ambientación y decoración del evento corre por cuenta de quienes contratan. Puede coordinarse gastronomía y coffee break previa conversación. Solicitar presupuesto con aproximadamente 15 días a un mes de anticipación.",

    /* ---------- Qué hacer ---------- */
    "q_titulo": "Caminatas, comunidad y paisajes del valle",
    "q_intro": "Desde la finca pueden coordinarse actividades para conocer el paraje San Antonio y sus alrededores: una caminata por las obras comunitarias de provisión de agua, visitas a petroglifos y pinturas con guía local y cabalgatas en la zona de Corralito. Algunas son organizadas por terceros y requieren reserva previa.",
    "q_act1_titulo": "Visita a las obras hidráulicas de provisión de agua a la comunidad",
    "q_act1_mini": "Una caminata sencilla para conocer cómo la comunidad gestiona el agua para consumo y riego mediante obras construidas durante 25 años.",
    "q_act1_texto": "Esta caminata permite conocer las obras que la comunidad de San Antonio desarrolló durante los últimos 25 años para abastecerse de agua para consumo y riego. El recorrido parte desde la zona de la finca, cruza el río y avanza entre uno y dos kilómetros por un terreno de dificultad muy baja. La actividad dura aproximadamente entre dos y tres horas y se coordina a pedido con al menos un día de anticipación. No tiene costo adicional para los huéspedes. Se recomienda llevar ropa cómoda y agua. Por sus características, no está indicada para personas adultas mayores.",
    "q_act2_titulo": "Visita a pinturas y petroglifos de la comunidad",
    "q_act2_mini": "Un recorrido con guía local por la ladera norte de los cerros para observar huellas precolombinas y conocer parte de la historia del valle.",
    "q_act2_texto": "La visita recorre la ladera norte de los cerros que rodean el valle de San Antonio para observar pinturas y petroglifos realizados por comunidades indígenas en época precolombina. La distancia desde el hotel es de aproximadamente tres a cuatro kilómetros y la actividad puede durar entre dos y tres horas y media. La dificultad es media por el ascenso de la ladera. Se realiza con un guía local, tiene costo adicional acordado directamente con él y debe reservarse con uno o dos días de anticipación. Llevar ropa cómoda, calzado adecuado y agua, y seguir las indicaciones del guía. Está recomendada desde los 10 años hasta personas adultas y puede realizarse durante todo el año. Esta actividad no es brindada directamente por Finca La Carla: es realizada por un guía local.",
    "q_act3_titulo": "Cabalgata en Corralito",
    "q_act3_mini": "Una jornada a caballo por paisajes de Corralito, coordinada con un emprendedor local. Finca La Carla facilita el contacto y la reserva.",
    "q_act3_texto": "La cabalgata se realiza en la zona de Corralito, a aproximadamente 18 kilómetros de la finca, y permite dedicar un día a recorrer paisajes del Valle Calchaquí a caballo. La dificultad es media y puede realizarse durante todo el año. La salida se organiza a pedido con el emprendedor local responsable de los caballos y tiene costo adicional, acordado directamente con él. Se recomienda reservar con al menos dos días de anticipación y llevar ropa cómoda y agua. Finca La Carla puede gestionar el contacto, mientras que la operación y las medidas de seguridad corresponden al prestador. Esta es una actividad de un tercero con quien se facilita la vinculación.",
    "ficha_duracion": "Duración",
    "ficha_dificultad": "Dificultad",
    "ficha_distancia": "Distancia",
    "ficha_modalidad": "Modalidad",
    "ficha_epoca": "Época",
    "ficha_reserva": "Reserva",
    "ficha_costo": "Costo",
    "ficha_llevar": "Llevar",
    "ficha_a_pedido": "A pedido",
    "ficha_todo_anio": "Todo el año",
    "ficha_sin_costo": "Sin costo adicional para huéspedes",
    "ficha_ropa_agua": "Ropa cómoda y agua",
    "ficha_ropa_calzado": "Ropa cómoda, calzado adecuado y agua",
    "ficha_consultar": "Consultar con el prestador",
    "ficha_val_obras_duracion": "2 a 3 horas",
    "ficha_val_obras_dificultad": "Muy baja",
    "ficha_val_obras_distancia": "1 a 2 km",
    "ficha_val_obras_epoca": "Todo el año",
    "ficha_val_obras_reserva": "Al menos un día antes",
    "ficha_val_obras_costo": "Sin costo adicional para huéspedes",
    "ficha_val_obras_llevar": "Ropa cómoda y agua",
    "ficha_val_petro_duracion": "Entre 2 y 3 horas y media",
    "ficha_val_petro_dificultad": "Media",
    "ficha_val_petro_distancia": "3 a 4 km desde la finca",
    "ficha_val_petro_epoca": "Todo el año, según coordinación con el prestador",
    "ficha_val_petro_reserva": "Uno o dos días antes",
    "ficha_val_petro_costo": "Consultar directamente con el guía local",
    "ficha_val_petro_llevar": "Ropa cómoda, calzado adecuado y agua",
    "ficha_val_cabal_duracion": "Un día",
    "ficha_val_cabal_dificultad": "Media",
    "ficha_val_cabal_distancia": "Aprox. 18 km hasta el lugar",
    "ficha_val_cabal_epoca": "Todo el año",
    "ficha_val_cabal_reserva": "Al menos dos días antes",
    "ficha_val_cabal_costo": "Consultar con el prestador",
    "ficha_val_cabal_llevar": "Ropa cómoda y agua",

    /* ---------- Quiénes somos ---------- */
    "nos_titulo": "Una finca construida con tiempo y propósito",
    "nos_texto": "La historia de Finca La Carla comenzó en 2003, cuando Diego, junto a Iris Gilbert, inició la plantación de frutales y la construcción de una casa pensada desde el comienzo con criterios de sustentabilidad. La finca estaba abandonada y todo se hizo desde cero, aprovechando piedra, madera, caña y adobe de la zona. La obra llevó cerca de veinte años y contó con el trabajo y los saberes de vecinos de la comunidad. Con el tiempo, Marcela, diseñadora textil y actual compañera de Diego, tuvo un papel central en el diseño y la ambientación de los espacios. Hoy ambos gestionan la posada y reciben personalmente a los huéspedes, buscando conservar una escala pequeña, una atención cercana y una relación respetuosa con la tierra y la comunidad.",

    /* ---------- Fotos ---------- */
    "fotos_titulo": "Fotos",
    "fotos_intro": "Un recorrido visual por Finca La Carla: la finca, su arquitectura, las habitaciones y todo lo que forma parte de la estadía.",
    "fotos_abrir": "Abrir galería",
    "fotos_exterior": "Exterior y finca",
    "fotos_arquitectura": "Arquitectura",
    "fotos_habitaciones": "Habitaciones",
    "fotos_bano": "Baños",
    "fotos_gastronomia": "Gastronomía",
    "fotos_desayuno": "Desayuno",
    "fotos_pileta": "Pileta",
    "fotos_recreacion": "Recreación",
    "fotos_eventos": "Eventos",
    "fotos_artesanias": "Artesanías y productos regionales",
    "fotos_livings": "Livings y espacios comunes",
    "fotos_galeria_arq": "Galería arquitectónica",
    "fotos_quienes": "Quiénes somos",
    "fotos_quehacer": "Qué hacer",
    "fotos_jardines": "Jardines / finca productiva",
    "fotos_sustentabilidad": "Sustentabilidad",

    /* ---------- Contacto ---------- */
    "contacto_titulo": "Reservas y consultas",
    "contacto_texto": "Para consultar disponibilidad o reservar, podés comunicarte directamente con Finca La Carla. Las reservas directas se gestionan principalmente por WhatsApp y también se reciben consultas por email. Antes de viajar, recomendamos consultar cualquier duda sobre el acceso, las comidas o los servicios que quieras coordinar.",
    "contacto_datos_titulo": "Datos oficiales",
    "contacto_direccion": "Dirección",
    "contacto_cp": "Código postal",
    "contacto_pais": "País",
    "contacto_whatsapp": "WhatsApp principal / Reservas",
    "contacto_cel2": "Teléfono celular 2",
    "contacto_email_general": "Email general",
    "contacto_email_reservas": "Email para reservas",
    "contacto_form_titulo": "Formulario de consulta",
    "contacto_form_nombre": "Nombre y apellido",
    "contacto_form_ingreso": "Fecha de ingreso",
    "contacto_form_egreso": "Fecha de egreso",
    "contacto_form_personas": "Cantidad de personas",
    "contacto_form_email": "Email",
    "contacto_form_mensaje": "Mensaje",
    "contacto_form_enviar": "Enviar",
    "contacto_form_whatsapp": "WhatsApp",
    "contacto_confirmacion": "Tu consulta se realizó con éxito. Te responderemos a la brevedad.",
    "contacto_whatsapp_auto": "Hola, quisiera consultar disponibilidad y recibir información para una estadía en Finca La Carla. Gracias.",

    /* ---------- Información útil ---------- */
    "info_titulo": "Información para preparar tu estadía",
    "info_intro": "Antes de llegar conviene conocer algunos datos prácticos. Finca La Carla tiene siete habitaciones, cinco en planta baja y dos en planta alta, todas con baño privado. El acceso incluye 7 km de ripio desde la Ruta 40 y normalmente puede hacerse con cualquier vehículo, sin necesidad de 4x4.",
    "info_checkin": "Check-in",
    "info_checkin_valor": "14:00. Puede coordinarse ingreso anticipado sujeto a disponibilidad y sin costo adicional mientras la habitación pueda entregarse.",
    "info_checkout": "Check-out",
    "info_checkout_valor": "12:00. Puede coordinarse salida posterior sujeto a disponibilidad y sin costo adicional mientras no se necesite la habitación para un nuevo ingreso.",
    "info_desayuno": "Desayuno",
    "info_desayuno_valor": "Incluido en todas las reservas.",
    "info_habitaciones": "Habitaciones",
    "info_habitaciones_valor": "7 habitaciones: 5 triples, 1 doble y 1 doble con cama matrimonial.",
    "info_capacidad": "Capacidad",
    "info_capacidad_valor": "Hasta 21 personas, contemplando camas adicionales según disponibilidad.",
    "info_pisos": "Pisos",
    "info_pisos_valor": "5 habitaciones en planta baja y 2 en planta alta. No hay ascensor.",
    "info_wifi": "Wi-Fi",
    "info_wifi_valor": "Starlink. Cobertura informada en toda la finca y apto para consultas habituales y trabajo remoto.",
    "info_calefaccion": "Calefacción",
    "info_calefaccion_valor": "Radiadores y bomba de calor.",
    "info_aire": "Aire acondicionado",
    "info_aire_valor": "No dispone.",
    "info_estacionamiento": "Estacionamiento",
    "info_estacionamiento_valor": "Propio y exterior, descubierto, gratuito, con capacidad aproximada para 7 u 8 vehículos.",
    "info_acceso": "Acceso",
    "info_acceso_valor": "Los últimos 7 km son de ripio por Ruta Provincial 307 desde el desvío de Ruta 40. Normalmente puede accederse con automóvil convencional y no se requiere 4x4. Durante lluvias torrenciales de verano pueden producirse cortes temporarios en vados.",
    "info_transporte": "Transporte público",
    "info_transporte_valor": "No hay transporte público regular hasta la finca. Pueden utilizarse remises, taxis o servicios de traslado de terceros coordinados previamente.",
    "info_altitud": "Altitud",
    "info_altitud_valor": "Aproximadamente 2.000 metros sobre el nivel del mar.",
    "info_ninos": "Niños",
    "info_ninos_valor": "Se reciben niños de todas las edades. Hay cunas disponibles.",
    "info_cama": "Cama adicional",
    "info_cama_valor": "Puede agregarse a pedido cuando la disponibilidad del hotel lo permita y siempre que el hotel no esté totalmente lleno. No tiene costo adicional.",
    "info_mascotas": "Mascotas",
    "info_mascotas_valor": "Se aceptan mascotas educadas. No tienen costo adicional.",
    "info_fumadores": "Fumadores",
    "info_fumadores_valor": "Permitido únicamente en espacios exteriores. Prohibido fumar dentro de habitaciones y espacios cerrados.",
    "info_accesibilidad": "Accesibilidad",
    "info_accesibilidad_valor": "La finca no está adaptada para personas con movilidad reducida debido a desniveles, terrazas y escaleras.",
    "info_equipaje": "Guardado de equipaje",
    "info_equipaje_valor": "Disponible sin costo.",
    "info_lavanderia": "Lavandería",
    "info_lavanderia_valor": "Disponible sin costo adicional para huéspedes con estadías prolongadas.",
    "info_traslados": "Traslados",
    "info_traslados_valor": "La finca no brinda traslados propios. Puede facilitar contactos de remises, taxis y prestadores locales.",
    "info_idiomas": "Idiomas de atención",
    "info_idiomas_valor": "Español e inglés.",
    "info_electricidad": "Electricidad",
    "info_electricidad_valor": "Paneles solares complementados por red eléctrica.",
    "info_agua": "Agua",
    "info_agua_valor": "Gestionada por la comunidad y tratada en condiciones de potabilidad dentro de la finca.",
    "info_temporada": "Temporada",
    "info_temporada_valor": "Abierto durante todo el año. No existe estadía mínima obligatoria informada.",

    /* ---------- FAQ ---------- */
    "faq_titulo": "Respuestas rápidas antes de tu estadía",
    "faq_intro": "Reunimos las consultas más habituales sobre cómo llegar, horarios, desayuno, Wi-Fi, estacionamiento, niños, mascotas, medios de pago y servicios.",
    "faq_p1": "¿El desayuno está incluido?",
    "faq_r1": "Sí. El desayuno está incluido en todas las reservas.",
    "faq_p2": "¿Puedo almorzar o cenar en la finca?",
    "faq_r2": "Sí. Los almuerzos y cenas se preparan a pedido y tienen costo adicional. Se recomienda solicitarlos con unas tres o cuatro horas de anticipación.",
    "faq_p3": "¿Cómo es el camino para llegar?",
    "faq_r3": "Desde Ruta 40 hay aproximadamente 7 km de camino de ripio por la Ruta Provincial 307. En condiciones normales puede realizarse con cualquier vehículo y no es necesaria una 4x4.",
    "faq_p4": "¿Qué ocurre si llueve mucho?",
    "faq_r4": "Las lluvias torrenciales de verano pueden afectar temporalmente algunos vados del camino. Ante condiciones climáticas especiales, consultar antes de viajar.",
    "faq_p5": "¿Hay estacionamiento?",
    "faq_r5": "Sí. Es descubierto, gratuito y tiene lugar aproximado para 7 u 8 vehículos.",
    "faq_p6": "¿Hay Wi-Fi?",
    "faq_r6": "Sí. La finca utiliza Starlink y la señal cubre el establecimiento.",
    "faq_p7": "¿Las habitaciones tienen televisión?",
    "faq_r7": "No. Hay un Smart TV de uso común en el estar.",
    "faq_p8": "¿Reciben niños?",
    "faq_r8": "Sí. Se reciben niños de todas las edades y hay cunas disponibles.",
    "faq_p9": "¿Se puede agregar una cama?",
    "faq_r9": "Sí, a pedido, cuando la disponibilidad del hotel lo permita y siempre que el hotel no esté totalmente lleno.",
    "faq_p10": "¿Aceptan mascotas?",
    "faq_r10": "Sí, siempre que sean educadas. No tienen costo adicional.",
    "faq_p11": "¿Está adaptada para personas con movilidad reducida?",
    "faq_r11": "No. Debido al terreno, los desniveles y las escaleras, los espacios no están adaptados para personas con movilidad reducida.",
    "faq_p12": "¿Se puede fumar?",
    "faq_r12": "Solamente en espacios exteriores. Está prohibido fumar dentro de las habitaciones y de los sectores cerrados.",
    "faq_p13": "¿Ofrecen traslados?",
    "faq_r13": "No se realizan traslados propios, pero se pueden facilitar contactos de remises y otros prestadores.",
    "faq_p14": "¿Hay lavandería?",
    "faq_r14": "Sí. Se ofrece sin costo adicional principalmente a quienes realizan estadías prolongadas.",
    "faq_p15": "¿Puedo dejar el equipaje?",
    "faq_r15": "Sí. Existe guardado de equipaje sin costo.",
    "faq_p16": "¿Qué medios de pago aceptan?",
    "faq_r16": "Habitualmente efectivo y transferencia. También se informó la utilización de PayPal y, en determinados casos, tarjeta.",
    "faq_p17": "¿Cómo se confirma una reserva directa?",
    "faq_r17": "Mediante un anticipo equivalente al 50 % del total de la estadía.",
    "faq_p18": "¿Cuál es la política de cancelación?",
    "faq_r18": "Si la cancelación se comunica con al menos 20 días de anticipación a la fecha de ingreso, se devuelve el dinero abonado. Si se cancela con menos de 20 días de anticipación, no se devuelve el anticipo.",
    "faq_p19": "¿Puedo reprogramar mi estadía?",
    "faq_r19": "Sí. La reprogramación debe solicitarse con al menos 20 días de anticipación a la fecha de ingreso. Con menos de 20 días de anticipación no corresponde reprogramación.",

    /* ---------- Sustentabilidad ---------- */
    "sust_titulo": "Sustentabilidad desde el origen",
    "sust_texto": "La sustentabilidad forma parte del diseño de Finca La Carla desde su origen. El establecimiento capta agua de lluvia y cuenta con sistemas de tratamiento y reutilización de aguas grises y negras para riego. Utiliza iluminación LED, calefones solares y paneles fotovoltaicos que generan hasta 15 kW durante el día, complementados por la red eléctrica cuando es necesario. Los residuos orgánicos se compostan y vuelven a la huerta, mientras que otros materiales se separan para su gestión. La producción es agroecológica, se aprovechan las podas como leña y se priorizan alimentos e insumos comprados en la comunidad.",
    "sust_1": "Captación de agua de lluvia",
    "sust_2": "Tratamiento y reutilización de aguas grises y negras",
    "sust_3": "Reutilización de agua para riego",
    "sust_4": "Iluminación LED",
    "sust_5": "Paneles solares (generación de aproximadamente 15 kW durante el día)",
    "sust_6": "Calefones solares",
    "sust_7": "Calefacción mediante radiadores y bomba de calor",
    "sust_8": "Utilización complementaria de electricidad de red",
    "sust_9": "Separación de residuos y plásticos",
    "sust_10": "Compostaje y aprovechamiento en almácigos y huerta",
    "sust_11": "Producción agroecológica",
    "sust_12": "Compra a productores de la comunidad",
    "sust_13": "Utilización como leña de material proveniente de podas de la propia finca",
    "sust_nota": "Finca La Carla no posee actualmente certificación ni sello de sustentabilidad.",

    /* ---------- Compromiso con la comunidad ---------- */
    "com_titulo": "Una relación cotidiana con San Antonio",
    "com_texto": "La finca trabaja de manera directa con la comunidad de San Antonio. Cuatro personas de familias del paraje participan en tareas productivas y de apoyo al hotel: tres mujeres y un hombre. También se compran alimentos e insumos a vecinos, se contacta a huéspedes con guías, remiseros y otros emprendedores locales y se difunden celebraciones como la Pachamama y la fiesta patronal de San Antonio. Diego participa además del consorcio de riego y administración de agua potable. La finca colabora con la escuela y el club local y busca que la actividad turística genere trabajo, compras y vínculos dentro de la comunidad.",
    "com_1": "Compra de carne y otros alimentos producidos localmente",
    "com_2": "Contratación o recomendación de guías locales",
    "com_3": "Contactos con remiseros y transportistas",
    "com_4": "Recomendación de productos elaborados en la comunidad",
    "com_5": "Difusión de la feria del puente durante el verano",
    "com_6": "Fiesta de la Pachamama",
    "com_7": "Fiesta patronal en honor a San Antonio",
    "com_8": "Colaboración con la escuela",
    "com_9": "Colaboración con el Club San Antonio",
    "com_10": "Participación en el consorcio de riego y administración del agua potable",

    /* ---------- Términos y condiciones ---------- */
    "term_titulo": "Términos y condiciones",
    "term_reservas_titulo": "Reservas",
    "term_reservas": "Las reservas directas se confirman mediante un anticipo equivalente al 50 % del valor total de la estadía.",
    "term_pagos_titulo": "Medios de pago",
    "term_pagos": "Se aceptan habitualmente efectivo y transferencia. También se informó la utilización de PayPal y, en determinados casos, tarjeta.",
    "term_checkin_titulo": "Check-in",
    "term_checkin": "A partir de las 14:00. Puede coordinarse ingreso anticipado sujeto a disponibilidad y sin costo adicional cuando la habitación pueda entregarse.",
    "term_checkout_titulo": "Check-out",
    "term_checkout": "12:00. Puede coordinarse salida posterior sujeto a disponibilidad y sin costo adicional cuando no exista necesidad de disponer de la habitación para un nuevo ingreso.",
    "term_desayuno_titulo": "Desayuno",
    "term_desayuno": "Incluido en la tarifa.",
    "term_almuerzos_titulo": "Almuerzos y cenas",
    "term_almuerzos": "Son opcionales, se coordinan previamente y tienen costo adicional.",
    "term_cancelaciones_titulo": "Cancelaciones",
    "term_cancelaciones": "Si la cancelación se comunica con al menos 20 días de anticipación a la fecha de ingreso, se devuelve el dinero abonado. Si se cancela con menos de 20 días de anticipación, no se devuelve el anticipo.",
    "term_reprog_titulo": "Reprogramaciones",
    "term_reprog": "Deben solicitarse con al menos 20 días de anticipación a la fecha de ingreso. Con menos de 20 días de anticipación no corresponde reprogramación.",
    "term_noshow_titulo": "No presentación",
    "term_noshow": "En caso de no presentarse, no se devuelve el anticipo realizado para confirmar la reserva.",
    "term_menores_titulo": "Menores",
    "term_menores": "Se reciben niños de todas las edades. Hay cunas disponibles. Los niños que utilicen la pileta deben permanecer bajo supervisión adulta.",
    "term_camas_titulo": "Camas adicionales",
    "term_camas": "Puede agregarse una cama adicional a pedido cuando la disponibilidad general del hotel lo permita y siempre que el hotel no esté totalmente lleno. No tiene costo adicional.",
    "term_mascotas_titulo": "Mascotas",
    "term_mascotas": "Se aceptan mascotas educadas sin costo adicional.",
    "term_fumadores_titulo": "Fumadores",
    "term_fumadores": "Está permitido fumar únicamente en espacios exteriores. No se permite fumar en habitaciones ni espacios cerrados.",
    "term_pileta_titulo": "Pileta",
    "term_pileta": "Es una pileta exterior de temporada. No cuenta con bañero. Los adultos responsables deben supervisar a los menores y se solicita evitar juegos bruscos.",
    "term_accesibilidad_titulo": "Accesibilidad",
    "term_accesibilidad": "Por las características del terreno, desniveles y escaleras, la finca no está adaptada para personas con movilidad reducida.",
    "term_externas_titulo": "Actividades externas",
    "term_externas": "Las actividades brindadas por guías, cabalgatas, transportistas u otros emprendedores son servicios de terceros. Las condiciones, precios y responsabilidad operativa corresponden al prestador respectivo. Finca La Carla puede facilitar el contacto y la coordinación.",
    "term_acceso_titulo": "Acceso",
    "term_acceso": "El tramo final comprende aproximadamente 7 km de ripio. Normalmente puede realizarse con vehículos convencionales. Las lluvias torrenciales pueden generar dificultades temporarias.",

    /* ---------- Política de cookies ---------- */
    "cookies_titulo": "Política de cookies",
    "cookies_def_titulo": "Definiciones y términos clave",
    "cookies_def_intro": "Para ayudar a explicar las cosas de la manera más clara posible en esta Política de cookies, cada vez que se hace referencia a cualquiera de estos términos, se definen estrictamente como:",
    "cookies_t_cookie": "Cookie:",
    "cookies_d_cookie": "pequeña cantidad de datos generados por un sitio web y guardados por su navegador web. Se utiliza para identificar su navegador, proporcionar análisis, recordar información sobre usted, como su preferencia de idioma o información de inicio de sesión.",
    "cookies_t_compania": "Compañía:",
    "cookies_d_compania": "cuando esta política menciona “Compañía”, “nosotros”, “nos” o “nuestro”, se refiere a Finca La Carla, responsable de su información en virtud de esta Política de Cookies.",
    "cookies_t_plataforma": "Plataforma:",
    "cookies_d_plataforma": "sitio web de Internet, aplicación web o aplicación digital de cara al público de Finca La Carla.",
    "cookies_t_dispositivo": "Dispositivo:",
    "cookies_d_dispositivo": "cualquier dispositivo conectado a Internet, como un teléfono, tablet, computadora o cualquier otro dispositivo que se pueda usar para visitar Finca La Carla y usar los servicios.",
    "cookies_t_datos": "Datos personales:",
    "cookies_d_datos": "cualquier información que directa, indirectamente o en conexión con otra información, incluido un número de identificación personal, permita la identificación de una persona física.",
    "cookies_t_servicio": "Servicio:",
    "cookies_d_servicio": "se refiere al servicio brindado por Finca La Carla como se describe en los términos relativos (si están disponibles) y en esta plataforma.",
    "cookies_t_terceros": "Terceros:",
    "cookies_d_terceros": "se refiere a anunciantes, patrocinadores de concursos, socios promocionales y de marketing, y otros que brindan nuestro contenido o cuyos productos o servicios que creemos que pueden interesarle.",
    "cookies_t_sitio": "Sitio web:",
    "cookies_d_sitio": "el sitio de Finca La Carla.",
    "cookies_t_usted": "Usted:",
    "cookies_d_usted": "una persona o entidad que está registrada con Finca La Carla para utilizar los Servicios.",
    "cookies_intro_titulo": "Introducción",
    "cookies_intro": "Esta Política de cookies explica cómo Finca La Carla y sus afiliados (colectivamente “Finca La Carla”, “nosotros”, “nos” y “nuestro”) utilizan cookies y tecnologías similares para reconocerlo cuando visita nuestra plataforma, incluidos, entre otros, Finca La Carla y cualquier URL relacionada, versiones móviles o localizadas y dominios / subdominios relacionados (“Sitios web”). Explica qué son estas tecnologías y por qué las usamos, así como las opciones de cómo controlarlas.",
    "cookies_que_titulo": "¿Qué es una Cookie?",
    "cookies_que": "Una cookie es un pequeño archivo de texto que se almacena en su computadora u otro dispositivo conectado a Internet para identificar su navegador, proporcionar análisis, recordar información sobre usted, como su preferencia de idioma o información de inicio de sesión. Son completamente seguros y no se pueden utilizar para ejecutar programas o enviar virus a su dispositivo.",
    "cookies_porque_titulo": "¿Por qué utilizamos Cookies?",
    "cookies_porque_intro": "Usamos cookies propias y / o de terceros en nuestra plataforma para varios propósitos, tales como:",
    "cookies_porque_1": "Para facilitar el funcionamiento y la funcionalidad de nuestra plataforma;",
    "cookies_porque_2": "Para mejorar su experiencia con nuestra plataforma y hacer que navegar alrededor de ellos sea más rápido y fácil;",
    "cookies_porque_3": "Para permitirnos crear una experiencia de usuario personalizada para usted y para que entendamos qué es útil o de su interés;",
    "cookies_porque_4": "Para analizar cómo se utiliza nuestra plataforma y cuál es la mejor forma de personalizarla;",
    "cookies_porque_5": "Para identificar prospectos futuros y personalizar las interacciones de marketing y ventas con él;",
    "cookies_porque_6": "Para facilitar la adaptación de la publicidad online a sus intereses.",
    "cookies_tipo_titulo": "¿Qué tipo de Cookies utiliza Finca La Carla?",
    "cookies_tipo": "Las cookies pueden ser cookies de sesión o cookies persistentes. Una cookie de sesión caduca automáticamente cuando cierra su navegador. Una cookie persistente permanecerá hasta que caduque o elimine sus cookies. Las fechas de caducidad se establecen en las propias cookies; algunos pueden caducar después de unos minutos, mientras que otros pueden caducar después de varios años. Las cookies colocadas por el sitio web que está visitando se denominan “cookies de origen”. Las cookies estrictamente necesarias son necesarias para que nuestra plataforma funcione y no se pueden desactivar en nuestros sistemas. Son esenciales para que pueda navegar por la plataforma y utilizar sus funciones. Si elimina o deshabilita estas cookies, no podemos garantizar que podrá utilizar nuestra plataforma.",
    "cookies_admin_titulo": "¿Cómo se pueden Administrar las Cookies?",
    "cookies_admin": "La mayoría de los navegadores le permiten controlar las cookies a través de sus preferencias de “configuración”. Sin embargo, si limita la capacidad de los sitios web para establecer cookies, puede empeorar su experiencia de usuario en general, ya que ya no estará personalizada para usted. También puede impedirle guardar configuraciones personalizadas como información de inicio de sesión. Los fabricantes de navegadores proporcionan páginas de ayuda relacionadas con la gestión de cookies en sus productos.",
    "cookies_cambios_titulo": "Cambios en nuestra Política de Cookies",
    "cookies_cambios": "Podemos cambiar nuestro Servicio y nuestras políticas, y es posible que debamos realizar cambios en esta Política de cookies para que reflejen con precisión nuestro Servicio y nuestras políticas. A menos que la ley exija lo contrario, le notificaremos (por ejemplo, a través de nuestro Servicio) antes de realizar cambios en esta Política de cookies y le daremos la oportunidad de revisarlos antes de que entren en vigencia. Luego, si continúa utilizando el Servicio, estará sujeto a la Política de cookies actualizada. Si no desea aceptar esta o cualquier Política de cookies actualizada, puede eliminar su cuenta.",
    "cookies_consentimiento_titulo": "Su consentimiento",
    "cookies_consentimiento": "Al utilizar nuestra plataforma, registrar una cuenta o realizar una compra, por la presente acepta nuestra Política de cookies y acepta sus términos.",
    "cookies_contacto_titulo": "Contáctenos",
    "cookies_contacto": "No dude en contactarnos si tiene alguna pregunta sobre nuestra Política de Cookies."
  },

  "en": {
    /* ---------- General ---------- */
    "reservar": "BOOK NOW",
    "enviar": "Send",
    "volver": "Back",
    "verMas": "See more",
    "leerMas": "Read more",
    "home": "Home",
    "cerrar": "Close",
    "anterior": "Previous",
    "siguiente": "Next",
    "direccion_corta": "Paraje San Antonio s/n, Animana, Salta, Argentina",
    "conocer": "Discover Finca La Carla",
    "descubrir": "Discover",
    "eyebrow_hero": "Boutique inn · Calchaquí Valley",
    "eyebrow_hero_sub": "San Antonio · Animana · Salta",
    "eyebrow_pres": "Welcome to San Antonio",
    "eyebrow_servicios": "Our proposal",
    "eyebrow_historia": "A family story",
    "eyebrow_ofrecemos": "Values that define us",
    "eyebrow_testimonios": "Guest experiences",
    "eyebrow_donde": "Our location",

    /* ---------- Navigation ---------- */
    "nav_home": "Home",
    "nav_habitaciones": "Rooms",
    "nav_gastronomia": "Gastronomy",
    "nav_servicios": "Services",
    "nav_eventos": "Events",
    "nav_quehacer": "Things to do",
    "nav_quienessomos": "About us",
    "nav_fotos": "Photos",
    "nav_contacto": "Contact",

    /* ---------- Hero ---------- */
    "hero_lema": "An earthly proposal",

    /* ---------- Brief presentation ---------- */
    "pres_titulo": "An earthly proposal",
    "pres_subtitulo": "Nature, production and rest in the Calchaquí Valley",
    "pres_texto": "Finca La Carla is a boutique inn in the village of San Antonio, Animana, surrounded by two hectares of agroecological production. Built with stone, wood and adobe, it combines a rustic and minimalist aesthetic with a sustainable outlook: solar energy, water reuse and produce from the farm that reaches the table. A place designed to slow down, rest and share.",
    "pres_boton": "Discover Finca La Carla",

    /* ---------- Our services ---------- */
    "servicios_titulo": "Our services",
    "serv_gastronomia": "Gastronomy",
    "serv_eventos": "Events",
    "serv_quehacer": "Things to do",
    "serv_recreacion": "Recreation",
    "serv_pileta": "Swimming pool",
    "serv_artesanias": "Crafts and regional products",
    "serv_livings": "Living areas and common spaces",
    "serv_galeria": "The gallery",
    "serv_informacion": "Useful information",
    "serv_faq": "Frequently asked questions",

    /* ---------- About us (summary) ---------- */
    "historia_titulo": "A story made slowly",
    "historia_texto": "Diego imagined this project in the early 2000s and built it over two decades together with people from the community. Today, with Marcela, he personally welcomes each guest and keeps shaping a farm where design, production and care for the environment are part of the same story.",
    "historia_enlace": "Discover our story",

    /* ---------- What we offer ---------- */
    "ofrecemos_titulo": "What we offer",
    "ofre_sust_titulo": "Real sustainability",
    "ofre_sust_texto": "Solar energy, water reuse, composting and agroecological production are part of the farm's daily operation.",
    "ofre_prod_titulo": "Our own production",
    "ofre_prod_texto": "Fruits, vegetables, jams, wines and ciders are born on the farm and reach breakfasts, lunches, dinners and products to take away.",
    "ofre_atencion_titulo": "Attention from its owners",
    "ofre_atencion_texto": "Diego and Marcela personally welcome and accompany guests, with close attention to every need.",
    "ofre_ritmo_titulo": "The rhythm of the valley",
    "ofre_ritmo_texto": "Nature, silence and an open landscape invite you to slow down and enjoy a peaceful stay in the village of San Antonio.",

    /* ---------- Testimonials ---------- */
    "testimonios_titulo": "Testimonials",
    "test_marcelo": "A dream place in the mountains to truly connect. Everything is very well cared for and well done. The warm and genuine attention of its owners, the food, the homemade sweets and the wines they make stand out.",
    "test_eugenia": "We stayed as a couple and from the first day the experience was wonderful. Diego and Marcela welcomed us with great warmth. We enjoyed the breakfasts, the dinners, the products harvested there and especially their wines.",
    "test_nelly": "Every space reflects a lot of work, love and good taste. The warmth with which they welcomed us was wonderful, the cleanliness impeccable, and we loved that so many products came straight from the land and the vegetable garden.",
    "test_maya": "Wonderful hosts, cozy and impeccable rooms, a charming atmosphere and incredibly delicious food. The farm is an oasis of relaxation with great attention to detail. I can't wait to come back.",
    "test_marie": "An exceptional, quiet, intimate and relaxing place, with an exquisite breakfast made with fresh ingredients and warm, welcoming owners. It was the best place of our two-and-a-half-month trip through South America.",

    /* ---------- Where we are ---------- */
    "donde_titulo": "Where we are",
    "donde_texto": "Finca La Carla is in the village of San Antonio, municipality of Animana, 18 km from Cafayate. The last 7 km are gravel road, between the foothills, carob trees and landscapes typical of the Calchaquí Valley.",
    "donde_direccion": "Paraje San Antonio s/n, Animana, Salta, Argentina.",
    "donde_abrir": "Open in Google Maps",

    /* ---------- Footer ---------- */
    "footer_navegacion": "Navigation",
    "footer_legal": "Legal",
    "footer_terminos": "Terms and conditions",
    "footer_cookies": "Cookie policy",
    "footer_sustentabilidad": "Sustainability",
    "footer_comunidad": "Community commitment",
    "footer_contacto": "Contact",
    "footer_whatsapp": "Main WhatsApp",
    "footer_cel": "Mobile phone 2",
    "footer_email_general": "General email",
    "footer_email_reservas": "Reservations",
    "footer_derechos": "© {año} Finca La Carla. All rights reserved.",

    /* ---------- Rooms ---------- */
    "hab_titulo": "Seven warm, simple rooms designed for rest",
    "hab_intro": "The seven rooms belong to a single category and share the rustic, minimalist character of the farm, with materials and tones linked to the earth. All have a private bathroom, radiator heating, Wi-Fi, wardrobe and hairdryer. Five are on the ground floor and two upstairs. Most are triples, and one of them offers a large window with views of the valley and the night sky.",
    "hab_galeria": "Room gallery",
    "hab_con_titulo": "All rooms include",
    "hab_con_1": "Private bathroom",
    "hab_con_2": "Toilet",
    "hab_con_3": "Bidet",
    "hab_con_4": "Radiator heating",
    "hab_con_5": "Wi-Fi",
    "hab_con_6": "Wardrobe",
    "hab_con_7": "Hairdryer",
    "hab_con_8": "Bed linen",
    "hab_con_9": "Towels",
    "hab_sin_titulo": "Rooms do not include",
    "hab_sin_1": "Television in the room",
    "hab_sin_2": "Air conditioning",
    "hab_sin_3": "Safety box",
    "hab_sin_4": "Minibar",
    "hab_sin_5": "Electric kettle",
    "hab_sin_6": "Coffee maker",
    "hab_smarttv": "There is a Smart TV only in a common area.",
    "hab_capacidad_titulo": "Capacity and layout",
    "hab_cap_triples": "5 triple rooms, with 1 double bed and 1 single bed.",
    "hab_cap_doble": "1 double room.",
    "hab_cap_doblem": "1 double room with 1 double bed.",
    "hab_cap_total": "Maximum total capacity: 21 people, considering the possibility of adding extra beds subject to availability.",
    "hab_cap_pb": "5 rooms on the ground floor.",
    "hab_cap_pa": "2 rooms on the upper floor, accessed by stairs.",
    "hab_cap_superficie": "Approximate area of each room: 18 m².",
    "hab_adicional_titulo": "Additional information",
    "hab_adic_1": "Extra bed on request when general availability allows and as long as the inn is not fully booked. No additional cost.",
    "hab_adic_2": "Cot on request, at no additional cost.",
    "hab_adic_3": "Room number 3 is the only one with a bathtub with jacuzzi.",
    "hab_adic_4": "Some rooms face the vineyard and others the entrance of the farm.",
    "hab_adic_5": "There is a room with a large window and views of the Calchaquí Valley, especially valued by couples and for the night view.",
    "hab_accesibilidad": "Due to unevenness and stairs, the facilities are not adapted for people with reduced mobility.",

    /* ---------- Gastronomy ---------- */
    "gastro_titulo": "Gastronomy",
    "gastro_intro": "Homemade flavours and products from our own farm",
    "gastro_acerca_titulo": "About our kitchen",
    "gastro_acerca": "Breakfast is included and includes coffee, milk, teas, toast, butter, homemade yogurt and granola, plus jams made on the farm with seasonal fruit. Depending on the day, pound cakes, cakes, sweet pastries and bollo bread from neighbours of the community are added. Lunches and dinners are prepared on request and have an additional cost: they can include goat cazuela, pies with garden produce, Arab empanadas and homemade pasta. There are also vegetarian, vegan and children's options on request, our own wines and ciders and picnic packs. Meals are coordinated in advance and aim to make the most of products from the farm and nearby producers.",
    "gastro_desayuno_titulo": "Breakfast",
    "gastro_desayuno_texto": "It is included in all reservations. It may include:",
    "gastro_desayuno_1": "Coffee",
    "gastro_desayuno_2": "Milk",
    "gastro_desayuno_3": "Different teas",
    "gastro_desayuno_4": "Toast",
    "gastro_desayuno_5": "Butter",
    "gastro_desayuno_6": "Homemade yogurt",
    "gastro_desayuno_7": "Homemade granola",
    "gastro_desayuno_8": "Pound cakes",
    "gastro_desayuno_9": "Cakes",
    "gastro_desayuno_10": "Sweet pastries",
    "gastro_desayuno_11": "Bollo bread made by neighbours",
    "gastro_mermeladas": "Homemade jams according to availability: apricot, peach, cayote, quince, plum, tomato and apple.",
    "gastro_almuerzos_titulo": "Lunches and dinners",
    "gastro_almuerzos_texto": "They do not work as an open restaurant with a permanent menu. They are prepared on request, have an additional cost and it is recommended to order them 3 or 4 hours in advance. A local cook can prepare the meals. Some of the dishes:",
    "gastro_plato_1": "Goat cazuela",
    "gastro_plato_2": "Pies or tarteletas with garden produce",
    "gastro_plato_3": "Preparations with zucchini and summer squash",
    "gastro_plato_4": "Arab empanadas",
    "gastro_plato_5": "Homemade pasta",
    "gastro_plato_6": "Ricotta, walnut and ham agnolotti",
    "gastro_plato_7": "Homemade noodles",
    "gastro_plato_8": "Bolognese sauce",
    "gastro_plato_9": "Filetto sauce",
    "gastro_plato_10": "Apple strudel made with apples from the farm",
    "gastro_plato_11": "Seasonal ice cream",
    "gastro_dietas_titulo": "Special diets",
    "gastro_dietas_texto": "Can be prepared on request: vegetarian menu, vegan menu and children's menu. There is currently no confirmed gluten-free (sin TACC) option.",
    "gastro_bebidas_titulo": "Drinks",
    "gastro_bebidas_1": "Wines made on the farm",
    "gastro_bebidas_2": "Ciders made on the farm",
    "gastro_bebidas_3": "Beer",
    "gastro_bebidas_4": "Soft drinks",
    "gastro_bebidas_5": "Water",
    "gastro_bebidas_6": "Soda",
    "gastro_bebidas_nota_1": "Water and soda are usually courtesy of the house.",
    "gastro_bebidas_nota_2": "Aguardiente, grappa and cognac can be offered on request during after-dinner conversation. There is a cellar with our own wines; there is no independent bar.",
    "gastro_viandas": "There is no room service. Picnic packs can be prepared for picnics, excursions or trips, with prior coordination.",

    /* ---------- Services ---------- */
    "serv_titulo": "Simple services, close attention and spaces to enjoy",
    "serv_intro": "The stay combines direct attention from Diego and Marcela with services designed to accompany rest: included breakfast, daily cleaning, free laundry on extended stays, luggage storage, Starlink Wi-Fi, parking, seasonal swimming pool, library, board games and common spaces. Meals, activities and third-party services can also be coordinated.",
    "serv_atencion_titulo": "Guest attention",
    "serv_atencion_texto": "Attention is provided directly by Diego and Marcela, from arrival and the explanation of how the house works to assistance with luggage, breakfasts and coordination of meals or activities.",
    "serv_atencion_1": "Daily cleaning",
    "serv_atencion_2": "Change of linen every two days or on request",
    "serv_atencion_3": "Free laundry for extended stays",
    "serv_atencion_4": "Free luggage storage",
    "serv_atencion_5": "Cots",
    "serv_atencion_6": "Contact with remises, local guides, tourism companies and horse riding when required",
    "serv_atencion_nota": "Transfers, vehicle rental, guided trekking and horse riding operated by third parties are not services of the farm itself.",
    "serv_recreacion_titulo": "Time to read, play and share",
    "serv_recreacion_texto": "Recreation within the farm is designed to enjoy time without rushing. In the common living room there is a library with different collections, board games and a shared Smart TV. Guests can borrow books, play with the family or choose a movie. Depending on the season and the farm's activity, it is also possible to take part in tasks related to the vegetable garden, the fruit or grape harvest and the making of preserves. Everything is included for guests and requires no prior booking.",
    "serv_pileta_titulo": "Swimming pool among trees and landscape",
    "serv_pileta_texto": "The outdoor pool measures approximately 7 x 4.5 metres and is 1.50 metres deep. It is used mainly during summer and also on some warm spring days. Its use is included for guests at no additional cost. The area has a solarium, sun loungers and natural shade from the trees; towels can be requested and drinks or snacks coordinated. From there you enjoy the opening towards the Calchaquí Valley and the proximity of the gallery and the park. There is no lifeguard, so children must remain under adult supervision and rough games are discouraged. The pool is not heated: heating it with a heat pump is only a project.",
    "serv_artesanias_titulo": "Products born on the farm",
    "serv_artesanias_texto": "The inn displays and sells products made from the farm's production: plum, apricot, quince, peach and cayote jams, organic honeys, wines, cider, aguardiente, cognac, brandy and dried fruits such as walnuts. There are also handmade pieces with designs by Marcela, including shawls, handbags, trousers, sweaters, shirts, ponchos and ruanas; some are knitted and others made of linen. Many of the foods and drinks sold are the same ones that are part of breakfasts, lunches, dinners and after-dinner conversations. The usual payment methods are cash and bank transfer.",
    "serv_livings_titulo": "Spaces to share without rushing",
    "serv_livings_texto": "The common spaces extend the warm, uncluttered character of the rooms. The kitchen, the breakfast room, the dining room and the living room with a wood-burning fireplace come together as places to rest, read, talk or share a meal. There is a library, board games and a shared Smart TV. The furniture, lamps, wood, stone and earth tones accompany a rustic and minimalist atmosphere, designed so that each space keeps its identity without losing simplicity.",
    "serv_galeria_titulo": "A gallery open to the Valley",
    "serv_galeria_texto": "The large gallery is one of the central spaces of Finca La Carla. From there a wide view opens towards the Calchaquí Valley and it connects the room area with the park and the pool. In spring and summer it becomes one of the favourite places to rest, chat and share meals. Its scale also allows it to host gatherings and group lunches. The stone, wood and natural tones maintain the rustic, sober language of the whole house.",

    /* ---------- Events ---------- */
    "eventos_titulo": "Gatherings surrounded by nature",
    "eventos_texto": "The farm hosts family gatherings, birthdays, baptisms, retreats, training sessions and group meetings. The large gallery has been used for lunches of more than 50 people and the park offers areas under the trees for outdoor activities. Tables, chairs, Wi-Fi and sound are available; when the event requires more equipment, the organisers can bring their own. Gastronomy or coffee break can be coordinated in advance. Quotes are requested approximately 15 days to a month in advance. Up to 21 people can stay in the seven rooms, considering additional beds subject to availability.",
    "eventos_nota_1": "The gallery and the park are the spaces used; there is no specific function room for events.",
    "eventos_equipo_titulo": "Confirmed equipment",
    "eventos_equipo_1": "Tables",
    "eventos_equipo_2": "Chairs",
    "eventos_equipo_3": "Wi-Fi",
    "eventos_equipo_4": "Sound",
    "eventos_nota_2": "The styling and decoration of the event is the responsibility of the organisers. Gastronomy and coffee break can be coordinated in advance. Request a quote approximately 15 days to a month in advance.",

    /* ---------- Things to do ---------- */
    "q_titulo": "Walks, community and valley landscapes",
    "q_intro": "From the farm, activities can be coordinated to get to know the village of San Antonio and its surroundings: a walk along the community water supply works, visits to petroglyphs and paintings with a local guide, and horse riding in the Corralito area. Some are organised by third parties and require prior booking.",
    "q_act1_titulo": "Visit to the hydraulic water supply works of the community",
    "q_act1_mini": "A simple walk to learn how the community manages water for consumption and irrigation through works built over 25 years.",
    "q_act1_texto": "This walk allows you to learn about the works that the San Antonio community developed over the last 25 years to supply itself with water for consumption and irrigation. The route starts from the farm area, crosses the river and advances between one and two kilometres over terrain of very low difficulty. The activity lasts approximately two to three hours and is coordinated on request with at least one day's notice. It has no additional cost for guests. Comfortable clothing and water are recommended. Due to its characteristics, it is not suitable for older adults.",
    "q_act2_titulo": "Visit to the community paintings and petroglyphs",
    "q_act2_mini": "A walk with a local guide along the northern slope of the hills to observe pre-Columbian traces and learn part of the valley's history.",
    "q_act2_texto": "The visit covers the northern slope of the hills surrounding the San Antonio valley to observe paintings and petroglyphs made by indigenous communities in pre-Columbian times. The distance from the inn is approximately three to four kilometres and the activity can last between two and three and a half hours. The difficulty is medium due to the ascent of the slope. It takes place with a local guide, has an additional cost agreed directly with him and must be booked one or two days in advance. Bring comfortable clothing, suitable footwear and water, and follow the guide's instructions. It is recommended from age 10 to adults and can be done all year round. This activity is not provided directly by Finca La Carla: it is carried out by a local guide.",
    "q_act3_titulo": "Horse riding in Corralito",
    "q_act3_mini": "A day on horseback through the landscapes of Corralito, coordinated with a local entrepreneur. Finca La Carla facilitates the contact and the booking.",
    "q_act3_texto": "The horse ride takes place in the Corralito area, approximately 18 kilometres from the farm, and allows you to spend a day exploring the landscapes of the Calchaquí Valley on horseback. The difficulty is medium and it can be done all year round. The departure is organised on request with the local entrepreneur in charge of the horses and has an additional cost, agreed directly with him. It is recommended to book at least two days in advance and bring comfortable clothing and water. Finca La Carla can arrange the contact, while the operation and safety measures are the responsibility of the provider. This is a third-party activity with whom the connection is facilitated.",
    "ficha_duracion": "Duration",
    "ficha_dificultad": "Difficulty",
    "ficha_distancia": "Distance",
    "ficha_modalidad": "Type",
    "ficha_epoca": "Season",
    "ficha_reserva": "Booking",
    "ficha_costo": "Cost",
    "ficha_llevar": "Bring",
    "ficha_a_pedido": "On request",
    "ficha_todo_anio": "All year round",
    "ficha_sin_costo": "No additional cost for guests",
    "ficha_ropa_agua": "Comfortable clothing and water",
    "ficha_ropa_calzado": "Comfortable clothing, suitable footwear and water",
    "ficha_consultar": "Check with the provider",
    "ficha_val_obras_duracion": "2 to 3 hours",
    "ficha_val_obras_dificultad": "Very low",
    "ficha_val_obras_distancia": "1 to 2 km",
    "ficha_val_obras_epoca": "All year round",
    "ficha_val_obras_reserva": "At least one day in advance",
    "ficha_val_obras_costo": "No additional cost for guests",
    "ficha_val_obras_llevar": "Comfortable clothing and water",
    "ficha_val_petro_duracion": "Between 2 and 3.5 hours",
    "ficha_val_petro_dificultad": "Medium",
    "ficha_val_petro_distancia": "3 to 4 km from the farm",
    "ficha_val_petro_epoca": "All year round, depending on coordination with the provider",
    "ficha_val_petro_reserva": "One or two days in advance",
    "ficha_val_petro_costo": "Check directly with the local guide",
    "ficha_val_petro_llevar": "Comfortable clothing, suitable footwear and water",
    "ficha_val_cabal_duracion": "One day",
    "ficha_val_cabal_dificultad": "Medium",
    "ficha_val_cabal_distancia": "Approx. 18 km to the place",
    "ficha_val_cabal_epoca": "All year round",
    "ficha_val_cabal_reserva": "At least two days in advance",
    "ficha_val_cabal_costo": "Check with the provider",
    "ficha_val_cabal_llevar": "Comfortable clothing and water",

    /* ---------- About us ---------- */
    "nos_titulo": "A farm built with time and purpose",
    "nos_texto": "The story of Finca La Carla began in 2003, when Diego, together with Iris Gilbert, started planting fruit trees and building a house conceived from the beginning with sustainability criteria. The farm was abandoned and everything was done from scratch, using stone, wood, cane and adobe from the area. The work took nearly twenty years and relied on the labour and knowledge of neighbours from the community. Over time, Marcela, a textile designer and Diego's current partner, played a central role in the design and decoration of the spaces. Today they both run the inn and personally welcome guests, seeking to preserve a small scale, close attention and a respectful relationship with the land and the community.",

    /* ---------- Photos ---------- */
    "fotos_titulo": "Photos",
    "fotos_intro": "A visual journey through Finca La Carla: the farm, its architecture, the rooms and everything that is part of the stay.",
    "fotos_abrir": "Open gallery",
    "fotos_exterior": "Exterior and farm",
    "fotos_arquitectura": "Architecture",
    "fotos_habitaciones": "Rooms",
    "fotos_bano": "Bathrooms",
    "fotos_gastronomia": "Gastronomy",
    "fotos_desayuno": "Breakfast",
    "fotos_pileta": "Swimming pool",
    "fotos_recreacion": "Recreation",
    "fotos_eventos": "Events",
    "fotos_artesanias": "Crafts and regional products",
    "fotos_livings": "Living areas and common spaces",
    "fotos_galeria_arq": "The architectural gallery",
    "fotos_quienes": "About us",
    "fotos_quehacer": "Things to do",
    "fotos_jardines": "Gardens / productive farm",
    "fotos_sustentabilidad": "Sustainability",

    /* ---------- Contact ---------- */
    "contacto_titulo": "Bookings and enquiries",
    "contacto_texto": "To check availability or book, you can contact Finca La Carla directly. Direct bookings are mainly managed by WhatsApp and enquiries are also received by email. Before travelling, we recommend checking any questions about access, meals or the services you would like to coordinate.",
    "contacto_datos_titulo": "Official details",
    "contacto_direccion": "Address",
    "contacto_cp": "Postal code",
    "contacto_pais": "Country",
    "contacto_whatsapp": "Main WhatsApp / Bookings",
    "contacto_cel2": "Mobile phone 2",
    "contacto_email_general": "General email",
    "contacto_email_reservas": "Bookings email",
    "contacto_form_titulo": "Enquiry form",
    "contacto_form_nombre": "First and last name",
    "contacto_form_ingreso": "Arrival date",
    "contacto_form_egreso": "Departure date",
    "contacto_form_personas": "Number of people",
    "contacto_form_email": "Email",
    "contacto_form_mensaje": "Message",
    "contacto_form_enviar": "Send",
    "contacto_form_whatsapp": "WhatsApp",
    "contacto_confirmacion": "Your enquiry was sent successfully. We will get back to you shortly.",
    "contacto_whatsapp_auto": "Hello, I would like to ask about availability and receive information for a stay at Finca La Carla. Thank you.",

    /* ---------- Useful information ---------- */
    "info_titulo": "Information to prepare your stay",
    "info_intro": "Before arriving it is good to know some practical details. Finca La Carla has seven rooms, five on the ground floor and two upstairs, all with private bathroom. The access includes 7 km of gravel road from Route 40 and can normally be done with any vehicle, without needing a 4x4.",
    "info_checkin": "Check-in",
    "info_checkin_valor": "14:00. Early check-in can be arranged subject to availability and at no additional cost as long as the room can be handed over.",
    "info_checkout": "Check-out",
    "info_checkout_valor": "12:00. Late check-out can be arranged subject to availability and at no additional cost as long as the room is not needed for a new arrival.",
    "info_desayuno": "Breakfast",
    "info_desayuno_valor": "Included in all reservations.",
    "info_habitaciones": "Rooms",
    "info_habitaciones_valor": "7 rooms: 5 triples, 1 double and 1 double with double bed.",
    "info_capacidad": "Capacity",
    "info_capacidad_valor": "Up to 21 people, considering additional beds subject to availability.",
    "info_pisos": "Floors",
    "info_pisos_valor": "5 rooms on the ground floor and 2 upstairs. There is no lift.",
    "info_wifi": "Wi-Fi",
    "info_wifi_valor": "Starlink. Coverage reported throughout the farm and suitable for regular enquiries and remote work.",
    "info_calefaccion": "Heating",
    "info_calefaccion_valor": "Radiators and heat pump.",
    "info_aire": "Air conditioning",
    "info_aire_valor": "Not available.",
    "info_estacionamiento": "Parking",
    "info_estacionamiento_valor": "Own, outdoor, uncovered, free parking, with approximate capacity for 7 or 8 vehicles.",
    "info_acceso": "Access",
    "info_acceso_valor": "The last 7 km are gravel road along Provincial Route 307 from the Route 40 turn-off. It can normally be accessed with a conventional car and a 4x4 is not required. During heavy summer rains there may be temporary closures at fords.",
    "info_transporte": "Public transport",
    "info_transporte_valor": "There is no regular public transport to the farm. Remises, taxis or third-party transfer services coordinated in advance can be used.",
    "info_altitud": "Altitude",
    "info_altitud_valor": "Approximately 2,000 metres above sea level.",
    "info_ninos": "Children",
    "info_ninos_valor": "Children of all ages are welcome. Cots are available.",
    "info_cama": "Extra bed",
    "info_cama_valor": "Can be added on request when hotel availability allows and as long as the inn is not fully booked. No additional cost.",
    "info_mascotas": "Pets",
    "info_mascotas_valor": "Well-behaved pets are accepted. No additional cost.",
    "info_fumadores": "Smoking",
    "info_fumadores_valor": "Only allowed in outdoor areas. Smoking inside rooms and enclosed spaces is prohibited.",
    "info_accesibilidad": "Accessibility",
    "info_accesibilidad_valor": "The farm is not adapted for people with reduced mobility due to unevenness, terraces and stairs.",
    "info_equipaje": "Luggage storage",
    "info_equipaje_valor": "Available free of charge.",
    "info_lavanderia": "Laundry",
    "info_lavanderia_valor": "Available at no additional cost for guests on extended stays.",
    "info_traslados": "Transfers",
    "info_traslados_valor": "The farm does not provide its own transfers. It can facilitate contacts of remises, taxis and local providers.",
    "info_idiomas": "Languages spoken",
    "info_idiomas_valor": "Spanish and English.",
    "info_electricidad": "Electricity",
    "info_electricidad_valor": "Solar panels supplemented by the electricity grid.",
    "info_agua": "Water",
    "info_agua_valor": "Managed by the community and treated under potable conditions within the farm.",
    "info_temporada": "Season",
    "info_temporada_valor": "Open all year round. There is no mandatory minimum stay reported.",

    /* ---------- FAQ ---------- */
    "faq_titulo": "Quick answers before your stay",
    "faq_intro": "We have gathered the most common questions about how to get here, timings, breakfast, Wi-Fi, parking, children, pets, payment methods and services.",
    "faq_p1": "Is breakfast included?",
    "faq_r1": "Yes. Breakfast is included in all reservations.",
    "faq_p2": "Can I have lunch or dinner at the farm?",
    "faq_r2": "Yes. Lunches and dinners are prepared on request and have an additional cost. It is recommended to order them about three or four hours in advance.",
    "faq_p3": "What is the road like to get here?",
    "faq_r3": "From Route 40 there are approximately 7 km of gravel road along Provincial Route 307. Under normal conditions it can be done with any vehicle and a 4x4 is not necessary.",
    "faq_p4": "What happens if it rains a lot?",
    "faq_r4": "Heavy summer rains can temporarily affect some fords on the road. In special weather conditions, check before travelling.",
    "faq_p5": "Is there parking?",
    "faq_r5": "Yes. It is uncovered, free and has space for approximately 7 or 8 vehicles.",
    "faq_p6": "Is there Wi-Fi?",
    "faq_r6": "Yes. The farm uses Starlink and the signal covers the property.",
    "faq_p7": "Do the rooms have a television?",
    "faq_r7": "No. There is a Smart TV for common use in the living room.",
    "faq_p8": "Do you receive children?",
    "faq_r8": "Yes. Children of all ages are welcome and cots are available.",
    "faq_p9": "Can an extra bed be added?",
    "faq_r9": "Yes, on request, when hotel availability allows and as long as the inn is not fully booked.",
    "faq_p10": "Do you accept pets?",
    "faq_r10": "Yes, as long as they are well-behaved. No additional cost.",
    "faq_p11": "Is it adapted for people with reduced mobility?",
    "faq_r11": "No. Due to the terrain, unevenness and stairs, the spaces are not adapted for people with reduced mobility.",
    "faq_p12": "Can I smoke?",
    "faq_r12": "Only in outdoor areas. Smoking inside the rooms and enclosed areas is prohibited.",
    "faq_p13": "Do you offer transfers?",
    "faq_r13": "We do not provide our own transfers, but contacts of remises and other providers can be arranged.",
    "faq_p14": "Is there laundry?",
    "faq_r14": "Yes. It is offered at no additional cost mainly to those on extended stays.",
    "faq_p15": "Can I leave my luggage?",
    "faq_r15": "Yes. Free luggage storage is available.",
    "faq_p16": "What payment methods do you accept?",
    "faq_r16": "Usually cash and bank transfer. The use of PayPal and, in certain cases, card was also reported.",
    "faq_p17": "How is a direct booking confirmed?",
    "faq_r17": "Through a deposit equivalent to 50% of the total stay.",
    "faq_p18": "What is the cancellation policy?",
    "faq_r18": "If the cancellation is communicated at least 20 days before the arrival date, the amount paid is refunded. If cancelled with less than 20 days' notice, the deposit is not refunded.",
    "faq_p19": "Can I reschedule my stay?",
    "faq_r19": "Yes. Rescheduling must be requested at least 20 days before the arrival date. With less than 20 days' notice, rescheduling is not possible.",

    /* ---------- Sustainability ---------- */
    "sust_titulo": "Sustainability from the origin",
    "sust_texto": "Sustainability has been part of the design of Finca La Carla from its origin. The property captures rainwater and has systems for treating and reusing grey and black water for irrigation. It uses LED lighting, solar water heaters and photovoltaic panels that generate up to 15 kW during the day, supplemented by the electricity grid when necessary. Organic waste is composted and returns to the vegetable garden, while other materials are separated for management. Production is agroecological, pruning waste is used as firewood and priority is given to food and supplies bought in the community.",
    "sust_1": "Rainwater harvesting",
    "sust_2": "Treatment and reuse of grey and black water",
    "sust_3": "Water reuse for irrigation",
    "sust_4": "LED lighting",
    "sust_5": "Solar panels (generation of approximately 15 kW during the day)",
    "sust_6": "Solar water heaters",
    "sust_7": "Heating with radiators and heat pump",
    "sust_8": "Supplementary use of grid electricity",
    "sust_9": "Separation of waste and plastics",
    "sust_10": "Composting and use in seedbeds and vegetable garden",
    "sust_11": "Agroecological production",
    "sust_12": "Purchase from community producers",
    "sust_13": "Use of pruning waste from the farm as firewood",
    "sust_nota": "Finca La Carla currently has no environmental certification or sustainability seal.",

    /* ---------- Community commitment ---------- */
    "com_titulo": "An everyday relationship with San Antonio",
    "com_texto": "The farm works directly with the community of San Antonio. Four people from families of the village take part in productive and support tasks for the inn: three women and one man. Food and supplies are also bought from neighbours, guests are put in touch with guides, remis drivers and other local entrepreneurs, and celebrations such as the Pachamama and the patron saint festival of San Antonio are promoted. Diego also takes part in the irrigation consortium and drinking water management. The farm collaborates with the school and the local club and seeks for tourism to generate work, purchases and connections within the community.",
    "com_1": "Purchase of meat and other food produced locally",
    "com_2": "Hiring or recommendation of local guides",
    "com_3": "Contacts with remis drivers and transporters",
    "com_4": "Recommendation of products made in the community",
    "com_5": "Promotion of the summer bridge fair",
    "com_6": "Pachamama celebration",
    "com_7": "Patron saint festival in honour of San Antonio",
    "com_8": "Collaboration with the school",
    "com_9": "Collaboration with Club San Antonio",
    "com_10": "Participation in the irrigation consortium and drinking water management",

    /* ---------- Terms and conditions ---------- */
    "term_titulo": "Terms and conditions",
    "term_reservas_titulo": "Bookings",
    "term_reservas": "Direct bookings are confirmed with a deposit equivalent to 50% of the total value of the stay.",
    "term_pagos_titulo": "Payment methods",
    "term_pagos": "Cash and bank transfer are usually accepted. The use of PayPal and, in certain cases, card was also reported.",
    "term_checkin_titulo": "Check-in",
    "term_checkin": "From 14:00. Early check-in can be arranged subject to availability and at no additional cost when the room can be handed over.",
    "term_checkout_titulo": "Check-out",
    "term_checkout": "12:00. Late check-out can be arranged subject to availability and at no additional cost when the room is not needed for a new arrival.",
    "term_desayuno_titulo": "Breakfast",
    "term_desayuno": "Included in the rate.",
    "term_almuerzos_titulo": "Lunches and dinners",
    "term_almuerzos": "They are optional, coordinated in advance and have an additional cost.",
    "term_cancelaciones_titulo": "Cancellations",
    "term_cancelaciones": "If the cancellation is communicated at least 20 days before the arrival date, the amount paid is refunded. If cancelled with less than 20 days' notice, the deposit is not refunded.",
    "term_reprog_titulo": "Rescheduling",
    "term_reprog": "Must be requested at least 20 days before the arrival date. With less than 20 days' notice, rescheduling is not possible.",
    "term_noshow_titulo": "No-show",
    "term_noshow": "In case of no-show, the deposit made to confirm the booking is not refunded.",
    "term_menores_titulo": "Children",
    "term_menores": "Children of all ages are welcome. Cots are available. Children using the pool must remain under adult supervision.",
    "term_camas_titulo": "Extra beds",
    "term_camas": "An extra bed can be added on request when general hotel availability allows and as long as the inn is not fully booked. No additional cost.",
    "term_mascotas_titulo": "Pets",
    "term_mascotas": "Well-behaved pets are accepted at no additional cost.",
    "term_fumadores_titulo": "Smoking",
    "term_fumadores": "Smoking is only allowed in outdoor areas. Smoking is not permitted in rooms or enclosed spaces.",
    "term_pileta_titulo": "Swimming pool",
    "term_pileta": "It is a seasonal outdoor pool. There is no lifeguard. Responsible adults must supervise minors and rough games are discouraged.",
    "term_accesibilidad_titulo": "Accessibility",
    "term_accesibilidad": "Due to the characteristics of the terrain, unevenness and stairs, the farm is not adapted for people with reduced mobility.",
    "term_externas_titulo": "External activities",
    "term_externas": "Activities provided by guides, horse riding, transporters or other entrepreneurs are third-party services. The conditions, prices and operational responsibility correspond to the respective provider. Finca La Carla can facilitate the contact and coordination.",
    "term_acceso_titulo": "Access",
    "term_acceso": "The final stretch includes approximately 7 km of gravel road. It can normally be done with conventional vehicles. Heavy rains can cause temporary difficulties.",

    /* ---------- Cookie policy ---------- */
    "cookies_titulo": "Cookie policy",
    "cookies_def_titulo": "Definitions and key terms",
    "cookies_def_intro": "To help explain things as clearly as possible in this Cookie Policy, each time any of these terms is referenced, they are strictly defined as:",
    "cookies_t_cookie": "Cookie:",
    "cookies_d_cookie": "small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you, such as your language preference or login information.",
    "cookies_t_compania": "Company:",
    "cookies_d_compania": "when this policy mentions “Company”, “we”, “us” or “our”, it refers to Finca La Carla, responsible for your information under this Cookie Policy.",
    "cookies_t_plataforma": "Platform:",
    "cookies_d_plataforma": "Finca La Carla's public-facing website, web application or digital application.",
    "cookies_t_dispositivo": "Device:",
    "cookies_d_dispositivo": "any device connected to the Internet, such as a phone, tablet, computer or any other device that can be used to visit Finca La Carla and use the services.",
    "cookies_t_datos": "Personal data:",
    "cookies_d_datos": "any information that, directly, indirectly or in connection with other information, including a personal identification number, allows the identification of a natural person.",
    "cookies_t_servicio": "Service:",
    "cookies_d_servicio": "refers to the service provided by Finca La Carla as described in the related terms (if available) and on this platform.",
    "cookies_t_terceros": "Third parties:",
    "cookies_d_terceros": "refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we believe may be of interest to you.",
    "cookies_t_sitio": "Website:",
    "cookies_d_sitio": "the Finca La Carla website.",
    "cookies_t_usted": "You:",
    "cookies_d_usted": "a person or entity that is registered with Finca La Carla to use the Services.",
    "cookies_intro_titulo": "Introduction",
    "cookies_intro": "This Cookie Policy explains how Finca La Carla and its affiliates (collectively “Finca La Carla”, “we”, “us” and “our”) use cookies and similar technologies to recognise you when you visit our platform, including, among others, Finca La Carla and any related URLs, mobile or localised versions and related domains / subdomains (“Websites”). It explains what these technologies are and why we use them, as well as the options for how to control them.",
    "cookies_que_titulo": "What is a Cookie?",
    "cookies_que": "A cookie is a small text file that is stored on your computer or another Internet-connected device to identify your browser, provide analytics, remember information about you, such as your language preference or login information. They are completely safe and cannot be used to run programs or send viruses to your device.",
    "cookies_porque_titulo": "Why do we use Cookies?",
    "cookies_porque_intro": "We use first-party and / or third-party cookies on our platform for various purposes, such as:",
    "cookies_porque_1": "To facilitate the operation and functionality of our platform;",
    "cookies_porque_2": "To improve your experience with our platform and make navigating around it faster and easier;",
    "cookies_porque_3": "To allow us to create a personalised user experience for you and to understand what is useful or of interest to you;",
    "cookies_porque_4": "To analyse how our platform is used and how best to personalise it;",
    "cookies_porque_5": "To identify future prospects and personalise marketing and sales interactions with them;",
    "cookies_porque_6": "To facilitate the adaptation of online advertising to your interests.",
    "cookies_tipo_titulo": "What type of Cookies does Finca La Carla use?",
    "cookies_tipo": "Cookies can be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. The expiration dates are set in the cookies themselves; some may expire after a few minutes, while others may expire after several years. Cookies placed by the website you are visiting are called “first-party cookies”. Strictly necessary cookies are necessary for our platform to function and cannot be switched off in our systems. They are essential for you to browse the platform and use its features. If you delete or disable these cookies, we cannot guarantee that you will be able to use our platform.",
    "cookies_admin_titulo": "How can Cookies be Managed?",
    "cookies_admin": "Most browsers allow you to control cookies through their “settings” preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, as it will no longer be personalised for you. It may also prevent you from saving personalised settings such as login information. Browser manufacturers provide help pages related to cookie management in their products.",
    "cookies_cambios_titulo": "Changes to our Cookie Policy",
    "cookies_cambios": "We may change our Service and our policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and our policies. Unless required by law, we will notify you (for example, through our Service) before making changes to this Cookie Policy and give you the opportunity to review them before they take effect. Then, if you continue to use the Service, you will be subject to the updated Cookie Policy. If you do not wish to accept this or any updated Cookie Policy, you can delete your account.",
    "cookies_consentimiento_titulo": "Your consent",
    "cookies_consentimiento": "By using our platform, registering an account or making a purchase, you hereby accept our Cookie Policy and agree to its terms.",
    "cookies_contacto_titulo": "Contact us",
    "cookies_contacto": "Feel free to contact us if you have any questions about our Cookie Policy."
  }
};
